### ISSUE TITLE
[Help]show the current in different color

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#115]
I use portable version of foobar2000.
I set the highlight color and it is still just scrolling with no color

Yes, both in metadata and .lrc file 
the other plugin works so that is not the problem 
it something with my config and
foo_openlyrics needs to change its defaults

![Capture1](https://user-images.githubusercontent.com/62152714/162470544-4e169921-e5f8-487d-9e83-93c66783deea.PNG)
![Capture2](https://user-images.githubusercontent.com/62152714/162470549-a7da5af9-a9ab-4762-a6e7-f6fd724743c1.PNG)
![Capture 3](https://user-images.githubusercontent.com/62152714/162470551-0cf2fe00-7025-4a18-a81e-a7ff1f662379.PNG)
![Capture](https://user-images.githubusercontent.com/62152714/162470554-63ebd450-b184-4a7d-8fab-b39ac619ef55.PNG)

```
Components loaded in: 0:00.844918
Configuration read in: 0:00.126346
foobar2000 v1.6.10 [portable]
Watching: X:\***
User Interface initialized in: 0:01.069011
FFmpeg version: 4.3.1
Startup time : 0:02.359752

WASAPI shared configuration: 192000 Hz, 2 channels (FL FR), 32 bps (float). Buffer size 4224 frames.
Opening track for playback: "X:\***\Hello Happiness.mp3"
Automatic resampling: using Resampler (dBpoweramp/SSRC)
```
.lrc file contents

```
[00:16.74]Music makes me sing
[00:18.91]Goodbye sadness
...
[03:38.00]Music makes me sing
[03:40.60]Goodbye sadness
[03:42.40]Hello happiness

```
UNSYNCED LYRICS Metadata

```
XXX||Music makes me sing
Goodbye sadness
Hello happiness
....
Goodbye sadness
Hello happiness
```

Tested Results. When Testing only one of these were applied as metadata as you said.

1. Metadata field **SYNCEDLYRICS** with timed Lyrics **WORKS**
2. **LYRICS**  with timed Lyrics **WORKS**
3. even in **UNSYBCEDLYRICS** metadata field with timed lyrics synced lyrics **WORKS**

4. But when using Just **.lrc** _**not even unsynced lyrics show**_ 

1. I have .lrc in the same directory with the song both with the same name.

2.  

> I wonder, if you edit lyrics (without the tags available, so it doesn't find anything), save them, and then restart foobar or play another track and come back (just so it reloads from fresh), does it find the lyrics you just saved? Does that save to the configuration directory to the expected file?

No lyrics shows when I deleted the metadata field and played it with foobar2000 but the lyricspanel was showing synced lyrics

foo_openlyrics can read it if it is in same directory? 

It is a common practice to have .lrc and some in same folder. 

LyricsPanel caches it in the foobar2000 folder iirc

Now I use [%fillename%]
I have "Save to the same directory as the track"

```
Opening track for playback: "X:\LongPath\Whatsername.mp3"
INFO-OpenLyrics: Failed to read search-avoidance info: Unsupported format or corrupted file
INFO-OpenLyrics: Initiate lyric search
INFO-OpenLyrics: Searching for lyrics...
INFO-OpenLyrics: Querying for lyrics in file://X:\LongPath\Whatsername .lrc...
INFO-OpenLyrics: Querying for lyrics in file://X:\LongPath\Whatsername .txt...
INFO-OpenLyrics: Found 0 lyrics in local files: file://X:\LongPath\Whatsername 
INFO-OpenLyrics: Failed to retrieve lyrics from source: Local files
INFO-OpenLyrics: Searching for lyrics in tag: LYRICS
INFO-OpenLyrics: Searching for lyrics in tag: SYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Found lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Successfully retrieved lyrics from source: Metadata tags
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Loaded lyrics already form a valid UTF-8 sequence
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: Lyric loading complete
```

```
INFO-OpenLyrics: Failed to read search-avoidance info: Unsupported format or corrupted file
INFO-OpenLyrics: Searching for lyrics for artist='Taylor Swift', album='Taylor Swift', title='Picture To Burn'...
INFO-OpenLyrics: Save file name format '[%filename% ]' with directory class 'TrackFileDirectory' evaluated to 'file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn '
INFO-OpenLyrics: Querying for lyrics in file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn .lrc...
INFO-OpenLyrics: Querying for lyrics in file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn .txt...
INFO-OpenLyrics: Found 0 lyrics in local files: file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn 
INFO-OpenLyrics: Failed to retrieve lyrics from source: Local files
INFO-OpenLyrics: Searching for lyrics in tag: LYRICS
INFO-OpenLyrics: Searching for lyrics in tag: SYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Found lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Successfully retrieved lyrics from source: Metadata tags
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Loaded lyrics already form a valid UTF-8 sequence
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: Lyric loading complete
```

**Comment by jacquesh** [comment]
This already happens and you can already configure the colour in the Display preferences page.

**Comment by Rexadev** [comment]
I set the highlight color and it is still just scrolling

**Comment by jacquesh** [comment]
Is this with synchronised lyrics? It doesn't with with unsynced lyrics because there's no way to tell which line to highlight.

**Comment by Rexadev** [comment]
Yes, both in metadata and .lrc file 
the other plugin works so that is not the problem 
it something with my config and
foo_openlyrics needs to change its defaults

**Comment by jacquesh** [comment]
Can you please post screenshots of all your openlyrics config pages?

Also could you please add the contents of your console after a minimal reproduction of the issue? So close & re-open foobar, play a track that has this issue for a few seconds, then copy the console contents (View -> Console).

Finally, just in case, if you could add the exact contents of the lyric text you're expecting it to use (you mention it exists both in metadata and a file).

**Comment by Rexadev** [comment]
![Capture1](https://user-images.githubusercontent.com/62152714/162470544-4e169921-e5f8-487d-9e83-93c66783deea.PNG)
![Capture2](https://user-images.githubusercontent.com/62152714/162470549-a7da5af9-a9ab-4762-a6e7-f6fd724743c1.PNG)
![Capture 3](https://user-images.githubusercontent.com/62152714/162470551-0cf2fe00-7025-4a18-a81e-a7ff1f662379.PNG)
![Capture](https://user-images.githubusercontent.com/62152714/162470554-63ebd450-b184-4a7d-8fab-b39ac619ef55.PNG)

```
Components loaded in: 0:00.844918
Configuration read in: 0:00.126346
foobar2000 v1.6.10 [portable]
Watching: X:\***
User Interface initialized in: 0:01.069011
FFmpeg version: 4.3.1
Startup time : 0:02.359752

WASAPI shared configuration: 192000 Hz, 2 channels (FL FR), 32 bps (float). Buffer size 4224 frames.
Opening track for playback: "X:\***\Hello Happiness.mp3"
Automatic resampling: using Resampler (dBpoweramp/SSRC)
```
.lrc file contents

```
[00:16.74]Music makes me sing
[00:18.91]Goodbye sadness
[00:20.93]Hello happiness
[00:25.26]Music makes me sing
[00:27.68]Goodbye sadness
[00:29.67]Hello happiness
[00:56.48]
[00:56.48]Music makes me sing
[00:58.38]Goodbye silence
[01:00.66]Hello happiness (hello!)
[01:04.59]Music makes me sing
[01:07.13]Goodbye silence (I'm so happy, yeah)
[01:09.12]Hello happiness
[01:13.31]
[01:13.31]It moves my body
[01:16.19]Yet frees my mind
[01:18.62]There ain't no question
[01:20.82]Ooh, it makes me high
[01:22.91]If you're feelin' unsure
[01:24.93]I've got your cure
[01:27.29]This music is yours
[01:29.32]And this beat is mine (hello)
[01:31.67]
[01:31.67]It moves my body
[01:33.64]Yet frees my mind
[01:35.95]There ain't no question (I'm so happy)
[01:38.80]Ooh, it makes me high
[01:40.42]If you're feelin' unsure
[01:42.64]I've got your cure
[01:45.30]This music is yours
[01:47.03]And this beat is mine
[01:48.96]
[01:48.96]Music makes me sing
[01:50.97]Goodbye silence (Hello happiness)
[01:53.22]Hello happiness
[01:57.11]Music makes me sing
[01:59.77]Goodbye silence (Make you dance, baby)
[02:02.00]Hello happiness (I wanna dance tonight)
[02:05.66]
[02:05.66]Music makes me sing
[02:08.36]Goodbye silence
[02:10.57]Hello happiness
[02:14.59]
[02:14.59]Take me back to the dance floor
[02:18.57]So I can dance away my blues
[02:22.89]Love is what I'm here for
[02:27.02]So don't give me no bad news
[02:31.55]Take me back to the dance floor
[02:36.44]So I can dance away my blues
[02:41.01]Love is what I'm here for
[02:44.53]So don't give me no bad news
[02:49.53]
[02:49.53]It moves my body
[02:52.84]Yet frees my mind (Goodbye!)
[02:54.93]There ain't no question (Goodbye, sadness)
[02:57.45]Ooh, it makes me high
[02:59.37]If you're feelin' unsure
[03:01.15]I've got your cure (I wanna dance, wanna dance)
[03:03.90]This music is yours (Wanna dance, wanna dance)
[03:05.63]And this beat is mine
[03:07.99]
[03:07.99]It moves my body
[03:10.39]Yet frees my mind
[03:12.17]There ain't no question
[03:14.50]Ooh, it makes me high (To the dance, to the dance floor)
[03:16.64]If you're feelin' unsure (To the dance floor, baby)
[03:18.77]I've got your cure
[03:21.12]This music is yours
[03:23.17]And this beat is mine
[03:25.10]
[03:25.10](I can dance away my blues)
[03:32.13]Dance away my blues
[03:36.13]I wanna dance away my blues
[03:38.00]
[03:38.00]Music makes me sing
[03:40.60]Goodbye sadness
[03:42.40]Hello happiness

```
UNSYNCED LYRICS Metadata

```
XXX||Music makes me sing
Goodbye sadness
Hello happiness
Music makes me sing
Goodbye sadness
Hello happiness

Music makes me sing
Goodbye silence
Hello happiness (hello!)
Music makes me sing
Goodbye silence (I'm so happy, yeah)
Hello happiness

It moves my body
Yet frees my mind
There ain't no question
Ooh, it makes me high
If you're feelin' unsure
I've got your cure
This music is yours
And this beat is mine (hello)

It moves my body
Yet frees my mind
There ain't no question (I'm so happy)
Ooh, it makes me high
If you're feelin' unsure
I've got your cure
This music is yours
And this beat is mine

Music makes me sing
Goodbye silence (Hello happiness)
Hello happiness
Music makes me sing
Goodbye silence (Make you dance, baby)
Hello happiness (I wanna dance tonight)

Music makes me sing
Goodbye silence
Hello happiness

Take me back to the dance floor
So I can dance away my blues
Love is what I'm here for
So don't give me no bad news
Take me back to the dance floor
So I can dance away my blues
Love is what I'm here for
So don't give me no bad news

It moves my body
Yet frees my mind (Goodbye!)
There ain't no question (Goodbye, sadness)
Ooh, it makes me high
If you're feelin' unsure
I've got your cure (I wanna dance, wanna dance)
This music is yours (Wanna dance, wanna dance)
And this beat is mine

It moves my body
Yet frees my mind
There ain't no question
Ooh, it makes me high (To the dance, to the dance floor)
If you're feelin' unsure (To the dance floor, baby)
I've got your cure
This music is yours
And this beat is mine

(I can dance away my blues)
Dance away my blues
I wanna dance away my blues

Music makes me sing
Goodbye sadness
Hello happiness
```

**Comment by jacquesh** [comment]
Another case where #37 would've been useful =/ That all looks pretty sensible and as expected.

This sounds like a dumb question but I'm struggling to see why this might not be working: Can you try (temporarily) deleting the lyrics in the tag (leaving just the lrc), so that we can be 100% sure that it is indeed loading the lrc file and not missing the file for some weird reason and falling back to the unsynced lyrics in the tag without anybody realising.

**Comment by Rexadev** [comment]
Tested Results. When Testing only one of these were applied as metadata as you said.

Metadata field just SYNCEDLYRICS with timed Lyrics WORKS
LYRICS  with timed Lyrics WORKS
even in UNSYBCEDLYRICS metadata field with timed lyrics synced lyrics WORKS

But when using Just .lrc not even unsynced lyrics show

**Comment by jacquesh** [comment]
Aha! Ok so then the actual problem is that its not finding the file when you expect it to. It doesn't highlight the current line because you mentioned initially that there were only unsynced lyrics in the tag and when it fails to find the file it falls back to the tag and gets unsynced lyrics (which can't be highlighted per-line).

The question then is "why doesn't it find the file?" As shown in your configuration screenshots, you've got it set to load from the configuration directory. So assuming the file is correctly located at "C:\Users\<username>\AppData\Roaming\foobar2000\lyrics\<artist tag> - <title tag>.lrc", it should find the file...

I wonder, if you edit lyrics (without the tags available, so it doesn't find anything), save them, and then restart foobar or play another track and come back (just so it reloads from fresh), does it find the lyrics you just saved? Does that save to the configuration directory to the expected file?

**Comment by Rexadev** [comment]
1. I have .lrc in the same directory with the song both with the same name.

2.  

> I wonder, if you edit lyrics (without the tags available, so it doesn't find anything), save them, and then restart foobar or play another track and come back (just so it reloads from fresh), does it find the lyrics you just saved? Does that save to the configuration directory to the expected file?

No lyrics shows when I deleted the metadata field and played it with foobar2000 but the lyricspanel was showing synced lyrics

**Comment by jacquesh** [comment]
> 1. I have .lrc in the same directory with the song both with the same name.

I don't understand. Do you mean that the .lrc file you're wanting to load is in the same directory as the audio file you want it to load with, and in particular is *not* in the fb2k config directory that I listed above?

**Comment by Rexadev** [comment]
foo_openlyrics can read it if it is in same directory? 

It is a common practice to have .lrc and some in same folder. 

https://getmusicbee.com/forum/index.php?topic=33576.0#:~:text=If%20your%20track%20has%20the%20file%20name%20%22The%20Rolling%20Stones%20%2D%20Gimme%20Shelter.mp3%22%20the%20lyric%20file%20should%20be%20%22The%20Rolling%20Stones%20%2D%20Gimme%20Shelter.txt%22%20(or%20%22The%20Rolling%20Stones%20%2D%20Gimme%20Shelter.lrc%22)

LyricsPanel caches it in the foobar2000 folder iirc

I use portable version of foobar2000.

**Comment by jacquesh** [comment]
LSP3 defaults to storing in the foobar2000 folder. OpenLyrics does the same.

If you want to load lyrics from the directory of the audio file you need to change the "Save Directory" to "same directory as the current track".

**Comment by Rexadev** [comment]
Also changed "File Name format " to "same as the file name of the track"
still not working
updated to version 1.1

**Comment by Rexadev** [comment]
@jacquesh 

> LSP3 defaults to storing in the foobar2000 folder. OpenLyrics does the same.

But it works

**Comment by jacquesh** [comment]
v1.1 has added debug logs. Can you please turn them on (on the "Display" preferences page), then open the console ("View -> Console"), clear it, search for lyrics on a track that has this problem, and post the contents of the console? That will at least confirm for us that its loading lyrics from the correct place.

**Comment by Rexadev** [comment]
Opening track for playback: "X:\LongPath\Whatsername.mp3"
INFO-OpenLyrics: Failed to read search-avoidance info: Unsupported format or corrupted file
INFO-OpenLyrics: Initiate lyric search
INFO-OpenLyrics: Searching for lyrics...
INFO-OpenLyrics: Querying for lyrics in file://X:\LongPath\Whatsername .lrc...
INFO-OpenLyrics: Querying for lyrics in file://X:\LongPath\Whatsername .txt...
INFO-OpenLyrics: Found 0 lyrics in local files: file://X:\LongPath\Whatsername 
INFO-OpenLyrics: Failed to retrieve lyrics from source: Local files
INFO-OpenLyrics: Searching for lyrics in tag: LYRICS
INFO-OpenLyrics: Searching for lyrics in tag: SYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Found lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Successfully retrieved lyrics from source: Metadata tags
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Loaded lyrics already form a valid UTF-8 sequence
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: Lyric loading complete

**Comment by jacquesh** [comment]
There you go, `X:\LongPath\Whatsername .lrc` doesn't exist. Does it load correctly if you put something in that file? Considering the space at the end, is it possible you've got `X:\LongPath\Whatsername.lrc` (without the space)?

**Comment by Rexadev** [comment]
1. I have X:\LongPath\Whatsername.lrc not X:\LongPath\Whatsername .lrc with a space
2. LyricsPanel Works

**Comment by jacquesh** [comment]
> LyricsPanel Works
Yes, you've said that several times now. This tells me that the correct data exists *somewhere* but not much else because both plugins have many options, many of which could cause this to stop working as you expect. 

So you have the file without the space, meaning the next question is "why is it looking for a space":
1. Your config screenshots above show the default file name format of `[%artist% - ][%title%]`, I assume this is still what you're using?
2. Your config screenshots above show you're using "Save to the configuration directory" but the logs show it trying to load from the track directory, can you confirm that you're current config has it on "Save to the same directory as the track"?
3. Do any of the tags for that track have trailing spaces? (Its possible the LSP3 is stripping them before searching)
4. If you add the trailing space to the filename you already have, does it load correctly?

**Comment by Rexadev** [comment]
1.
> Your config screenshots above show the default file name format of [%artist% - ][%title%], I assume this is still what you're using?
Now I use [%fillename%]
Also Change it from "Default Save format" to "Default Save/Read Fomart"

2. Yes, now I have "Save to the same directory as the track"
3.
> Do any of the tags for that track have trailing spaces? (Its possible the LSP3 is stripping them before searching)

What? I don't understand.

4.  
> If you add the trailing space to the filename you already have, does it load correctly?

Yes

**Comment by Rexadev** [comment]
@jacquesh

**Comment by jacquesh** [comment]
I saw your message when you posted it on the 25th, no need to @ me :)

Honestly I'm running out of ideas. Nobody else has complained about this, suggesting that its something specific to your setup.
I added some extra debug logs in v1.2 that would answer question 3 from above, so if you could post new logs that might help.

**Comment by Rexadev** [comment]
INFO-OpenLyrics: Failed to read search-avoidance info: Unsupported format or corrupted file
INFO-OpenLyrics: Searching for lyrics for artist='Taylor Swift', album='Taylor Swift', title='Picture To Burn'...
INFO-OpenLyrics: Save file name format '[%filename% ]' with directory class 'TrackFileDirectory' evaluated to 'file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn '
INFO-OpenLyrics: Querying for lyrics in file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn .lrc...
INFO-OpenLyrics: Querying for lyrics in file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn .txt...
INFO-OpenLyrics: Found 0 lyrics in local files: file://X:\xx\#1 Taylor Swift (2006)\Picture To Burn 
INFO-OpenLyrics: Failed to retrieve lyrics from source: Local files
INFO-OpenLyrics: Searching for lyrics in tag: LYRICS
INFO-OpenLyrics: Searching for lyrics in tag: SYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Found lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Successfully retrieved lyrics from source: Metadata tags
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Loaded lyrics already form a valid UTF-8 sequence
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: Lyric loading complete

**Comment by Rexadev** [comment]
> Nobody else has complained about this, suggesting that its something specific to your setup.

Trying posting on Reddit and Hydrogen.
People how couldn't get this plugin to work must have switched to the LyricsPanel3.

**Comment by jacquesh** [comment]
> INFO-OpenLyrics: Save file name format '[%filename% ]' with directory class 'TrackFileDirectory' evaluated to 'file://X:\xx#1 Taylor Swift (2006)\Picture To Burn '

You've got it configured to look for `[%filename% ]` which has the extra space. Try with just `[%filename%]`.

**Comment by Rexadev** [comment]
Solved

**Comment by Rexadev** [comment]
You should change the default behavior to read in the same directory and of filename sidecar .lrc.
My Issue is resolved!
