### ISSUE TITLE
Support embedded and external subtitles

### ISSUE THREAD

**Issue by mzso** [jacquesh/foo_openlyrics#118]
Hi!

I'd would just like to mention that it would be nice if this plugin could show embedded subtitles, and external ones. It would be useful sometimes. For example I can download music/podcasts (or other audio centric videos) with subtitles (lyrics) from youtube via yt-dlp. It can embed subtitles into videofiles, or alternatively it can create it as an external file (including the lrc format in this case). Chapters, are conveniently already supported by foobar.

But I only could get it to view with this plugin if I place it in the proper folder in the proper format and naming convention manually.

**Comment by jacquesh** [comment]
I'll be honest this is unlikely to happen any time soon (if at all) but I'll leave the issue here in case others want it or I'm feeling inspired at some point.

**Comment by jacquesh** [comment]
Subtitle formats not commonly used for lyrics are out of scope for openlyrics.
