### ISSUE TITLE
Cannot Sync line using 'offset' tag, as it believes there is no timestamp.

### ISSUE THREAD

**Issue by u12bdragon** [jacquesh/foo_openlyrics#120]
No matter how the line is formatted, It shows an error saying "The currently-selected line does not have a timestamp" whenever I click the "Sync line using 'offset' tag" button

[https://i.imgur.com/3U7WV1L.png](https://i.imgur.com/3U7WV1L.png)

**Comment by jacquesh** [comment]
Dupe of #107, already fixed for the next release
