### ISSUE TITLE
Feature request: Remove asian text in brackets

### ISSUE THREAD

**Issue by HeresJonny** [jacquesh/foo_openlyrics#126]
Some sources add information in asian text like this
[00:00.00]I Will - Alison Krauss (艾莉森·克劳丝)/Tony Furtado
which in this case I suppose is the artist's name in Chinese.

In any case, those look like double byte characters so they should't be too hard to filter out (space bracket text bracket)

**Comment by HeresJonny** [comment]
Just to be clear, this should be an edit/auto-edit option.
Those pesky texts are also somtimes added on instrumentals like so 
[00:00.00]此歌曲为没有填词的纯音乐，请您欣赏&#13&#10
= This song is pure music without words, please enjoy & # 13 & # 10

If a [00:00.00] and nothing else exists with asian text that should be blocked/deleted
or maybe it could be replaced by text, even user selectable like "- instrumental -"

**Comment by jacquesh** [comment]
Your second use-case (regarding instrumental tracks) is already solved. There is already a "Mark as instrumental" auto-edit.

For your first use-case: Yes, technically I could add an auto-edit to remove non-latin/ASCII characters, but I don't think it would really solve the problem much of the time. Your example line would become `[00:00.00]I Will - Alison Krauss ()/Tony Furtado` and in particular I imagine you would want to go and remove those brackets too, but you'd have to do that manually (I'm not adding in special cases like "if there are brackets around the non-ASCII characters then remove those too"), in which case you're still having to make manual edits so the auto-edit hasn't actually helped.

This is a common problem with requests like this. As it happens the lyric that I currently have displaying on my fb2k starts with this line: `能把pop推嚮無底的深淵的力量`. Again, removing non-ASCII characters would clean it up somewhat, but I'd still have to go and manually edit it and so the auto-edit isn't actually helping much. Either way I have to go in and manually remove that line. So I don't believe the auto-edit is much of a help and so I don't think its worth adding.

**Comment by HeresJonny** [comment]
Kodi has an addon "CU Lyrics" with an option to remove asian text. I'll try to have a look at the code to see how they tackled the problem.

**Comment by HeresJonny** [comment]
Ok looks like they're just removing certain characters like this

              # replace CJK and fullwith colon (not present in many font files)
                lyrics.lyrics = re.sub(r'[ᄀ-ᇿ⺀-⺙⺛-⻳⼀-⿕々〇〡-〩〸-〺〻㐀-䶵一-鿃豈-鶴侮-頻並-龎]+', '', lyrics.lyrics).replace('：',':') 

but I lack the deeper understanding of the why.

**Comment by jacquesh** [comment]
Yeah see I that wouldn't actually require any less manual editing. It would remove those characters but not any of the text around it. You'd still need to remove those manually and once you're doing that it wouldn't actually be more effort to remove those characters yourself.

I don't think there is a good solution for automatically removing "the text you don't want" because that's not a reasonably-automatically-characterisable thing.

**Comment by HeresJonny** [comment]
I concur. Maybe it would be possible to add user definable chunks to auto-edit. That way no logic would be needed and each user could get rid of their own personal demons :-)
