### ISSUE TITLE
Regression: Embedded Lyrics are missing last line

### ISSUE THREAD

**Issue by Zapeth** [jacquesh/foo_openlyrics#127]
Not sure if only embedded lyrics are affected, but with the newly released version (v1.1), the last line is not displayed anymore.

With v1.0 it works as expected (the entire lyrics are displayed).

**Comment by jacquesh** [comment]
Ah, by embedded lyrics you mean those loaded from tags? Yeah I can reproduce that too. Thanks for reporting!

**Comment by elandorr** [comment]
PSA Saving is also affected. If you recently tagged a bunch, you'll have to redo!

**Comment by jacquesh** [comment]
Thanks for mentioning that @elandorr, that bumps the priority somewhat so I've fixed that now and I'll try get a new release out soon to minimise the damage
