### ISSUE TITLE
Feature suggestion: Listening sync

### ISSUE THREAD

**Issue by HeresJonny** [jacquesh/foo_openlyrics#128]
There's a project that is able to sync subtitles for movies/tv shows by analyzing spoken context: https://subsync.online/
I wonder how this would fare with music and lyrics... it would probably depend on the type of music and how much frequencies could be filtered.

**Comment by jacquesh** [comment]
Oh thats pretty neat. Unfortunately it relies on machine learning which is seldom done directly in C++ and I'm not embedding python into OpenLyrics. If I got into ML at some point it would be an interesting project to try replicate but for now it's not happening.

**Comment by jacquesh** [comment]
Actually, I'm closing this because realistically I'm never going to do it. This seems like a job for a separate tool that turns a track with unsynced lyrics into synced lyrics.
