### ISSUE TITLE
Force Explicit lyrics from providers

### ISSUE THREAD

**Issue by Noobgamer0111** [jacquesh/foo_openlyrics#131]
Is there any way of searching for Explicit versions of lyrics? I've used the "search for lyrics (manual)" button, but is there a way to force the software to grab the explicit lyrics for an album?

**Comment by jacquesh** [comment]
There is not, in general OpenLyrics doesn't specify this sort of thing, it just gives back whatever the relevant source provided.

If you know of a source that does actually provide such a switch that openlyrics is not currently using, then I could look into that but in the general case this is not something that we can do.
