### ISSUE TITLE
@jacquesh Want to help with format specs for SyncedLyrics-.lrc_v2?

### ISSUE THREAD

**Issue by marz1877** [jacquesh/foo_openlyrics#137]
https://github.com/marz1877/SyncedLyrics-.lrc_v2

**Comment by jacquesh** [comment]
No.

* This is a proposal for a new format for which, as far as I'm aware, there are no sources (at all, let alone good ones)
* People already have enough trouble getting lyrics annotated with just timestamps, nevermind all of this extra data you want to support
* It would introduce a huge amount of additional complexity to openlyrics for marginal benefit

**Comment by Rexadev** [comment]
> This is a proposal for a new format for which, as far as I'm aware, there are no sources (at all, let alone good ones)

MusixMatch has translation, Genius has meaning

> It would introduce a huge amount of additional complexity to openlyrics for marginal benefit

No it will make it even better


I like the .lrc v2

**Comment by marz1877** [comment]
@jacquesh A lot has changed in machine learning in last few months and much of the task can be automated. Will you help with the specs
