### ISSUE TITLE
Feature suggestion: Exclude tracks by genre

### ISSUE THREAD

**Issue by HeresJonny** [jacquesh/foo_openlyrics#142]
Some type of music will always be instrumental, like most Jazz and classical music. It would be great to exclude tracks by genre (user definable) from automated and batch searches.

**Comment by jacquesh** [comment]
I'm not sure this would be worth the additional complexity.

Tracks without lyrics will eventually become excluded automatically by virtue of lyrics not being found in the regular autosearches. If you really want to skip those tracks you can always manually mark them as instrumental. This would be even simpler to do in bulk with #113

**Comment by HeresJonny** [comment]
This feature would save some calls, though... the online databases would probably appreciate it.

**Comment by jacquesh** [comment]
I think #202 would be a better implementation of this, since it would provide the flexibility to do exactly what you suggest here but without being tied specifically to genre (so users can check the genre tag if they want, but could also check their own custom tag, or the file path, or whatever).
