### ISSUE TITLE
Auto download not work

### ISSUE THREAD

**Issue by GongT** [jacquesh/foo_openlyrics#144]
But search manually and download works well.

I can successfully open this url in browser and `invoke-webrequest` from terminal.

```
WARN-OpenLyrics: Failed to download netease page https://music.163.com/api/search/get?s=%E8%B8%8F%E4%BA%91%E7%A4%BE%2F%E8%A8%80%E5%92%8C%2F%E2%91%A2%E2%91%A0+%E5%A5%BD%E5%A5%87%E4%B8%8E%E5%8B%87%E6%B0%94&type=1&offset=0&sub=false&limit=5: Network authentication error (80090304)
```

**Comment by jacquesh** [comment]
When it comes to the actual network request, all the different searches function identically.

Please can you provide more information: Exactly what are the tags (artist/album/track) that its searching for? Exactly what do you mean by "doesn't work"? Can you post more complete logs? etc

**Comment by GongT** [comment]
After some google, I found it's wine issue, SSL1.2 not work, unknown reason.

it seems automatic search did not try QQMusic.
