### ISSUE TITLE
Add conversion to Traditional Chinese

### ISSUE THREAD

**Issue by theonen00b** [jacquesh/foo_openlyrics#146]
I notice that extension gets Chinese songs through sources using Simplified characters. As I prefer reading Traditional characters it would be good if you could implement an option to convert the lyrics to Traditional characters. Using a project such as [https://github.com/BYVoid/OpenCC](url) is an option.  

Also when I have a song title in Traditional Chinese it is only possible to get the lyrics when searching for them manually (the result will be in Simplified regardless).

**Comment by jacquesh** [comment]
No, this is beyond the scope of OpenLyrics.

You are free to make these edits manually using the available editor or use (or build) a separate tool to operate on the tags/text files saved by open lyrics. Scanning over the docs for OpenCC, it seems like it would be pretty simple to build a separate tool to do exactly this (or possibly even just use the command line tools that it comes with).
