### ISSUE TITLE
QQ Music Lyric search is not working

### ISSUE THREAD

**Issue by Sevenuno** [jacquesh/foo_openlyrics#148]
I set QQ music as one of the source and it used to work.  It stopped working since a few days ago.
I even tried to do manual search for the lyric of a song, which I've already downloaded the lyric from QQ, and it shows no result from QQ.

**Comment by jacquesh** [comment]
Indeed QQMusic searches are now returning 404. Does anybody know if there are other plugins that still retrieve from QQMusic successfully (e.g eslyric)? I assume that either they've changed their API in some way or made it inaccessible.

**Comment by nikop** [comment]
`https://c.y.qq.com/splcloud/fcgi-bin/smartbox_new.fcg?key=Good%20Morning%20[New]%20World!`

Seems to work for search. Lyric api doesn't seem to be changed.

**Comment by jacquesh** [comment]
Thanks @nikop openlyrics currently uses a different url/api though. Where did you get that url from? Is there any documentation or other code that is currently using it?

**Comment by nikop** [comment]
@jacquesh I did search from website and looked from network requests.

**Comment by Noobgamer0111** [comment]
Potentially relevant: https://developer.y.qq.com/docs/openapi#/overview
https://developer.y.qq.com/docs/openapi#/feature/accompany

You need to register on their site, and then you can use their API to pull lyrics.
