### ISSUE TITLE
Ok and Apply do the same thing

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#152]
![image](https://user-images.githubusercontent.com/62152714/180288462-5a4c275a-7d82-455b-b7af-4c8a502f52de.png)

**Comment by jacquesh** [comment]
Not true, "OK" closes the window.

**Comment by Rexadev** [comment]
I have testes id OK and Apply both saves

**Comment by Rexadev** [comment]
Ok - only applies to current playback
Apply - Saves

**Comment by Rexadev** [comment]
Change to -
`Apply` to `Save to Metadata`
`OK` to `Select for current playback`

@jacquesh
