### ISSUE TITLE
Search and fetch local lyrics (.lrc files) located in same directory as the .mp3 file

### ISSUE THREAD

**Issue by Sacolevas** [jacquesh/foo_openlyrics#154]
Hello, 

I am testing foobar in Windows as a possible default music player. However the feature that is keeping me using other players instead of foobar is the impossibility to see all the lyrics I have saved before in my computer (specially because these lyrics are not available in the usual lyric sites -lyrics of French, Portuguese, Russian and Hebrew songs-). I have many files like in the form "File name.mp3" with the corresponding .lrc file "File name.lrc" in the same folder (.lrc extension, same file name as the mp3 file), and this component is still unable to fetch those lyrics. 

I thought that maybe the plugin prioritize internet sources, so I tried only enabling "Local files" as the lyric source, but still doesn't work.

The only way I could see those lyrics was the following: 

1) Change the name of the .lrc file in the format "Artist - Title" (the only way I could) instead of the file name I have specified. 
2) Put this .lrc file in the folder "...\AppData\Roaming\foobar2000\lyrics" (if I keep the file in the same folder as the mp3 file, it doesn't work).  

But I can't repeat this process of renaming and move file to the foobar200\lyrics folder for hundreds of .lrc files!

Is there a way to fix this? Being able to read the .lrc file when it has the same name as the mp3 file and located in the same folder?

Thanks in advance

**Comment by jacquesh** [comment]
Have you tried setting the local file save directory (config -> OpenLyrics -> Saving) to "Save to the same directory as the track" and then setting the file name format (on the same page) to "%filename%" as explained in the linked "Syntax help" page? That should do what you want.

I confess the naming is a tad confusing but its not clear how to communicate in settings that files will be loaded from the save path.

**Comment by Sacolevas** [comment]
Thanks a lot!!! So it was not a missing feature but just some documentation I didn't see. Actually, I didn't realize there were arrows in the OpenLyrics item when I looked for foobar preferences, so when you wrote "(config -> OpenLyrics -> Saving)", I realized I didn't see most of the options I care about.

Thanks again!

**Comment by apprenti-sorcier** [comment]
When I set it with %filename%, some of the existant lyrics show this instead of the file content. I don’t see any difference to the other files that are shown fine.
![Image du presse-papiers](https://github.com/user-attachments/assets/6f729719-d6ab-4b29-9fd9-3e6ce1032182)
All these files are shown fine by the Lyric Show 3.
I even removed all the possible Internet sources so that there is no Chinese interference, but it’s not that either.
What is the problem ?

**Comment by jacquesh** [comment]
@apprenti-sorcier Please open a new ticket (with all the requested info from the template) rather than reviving a 2-year-old closed ticket :)

**Comment by yashj23** [comment]
> When I set it with %filename%, some of the existant lyrics show this instead of the file content. I don’t see any difference to the other files that are shown fine. ![Image du presse-papiers](https://github.com/user-attachments/assets/6f729719-d6ab-4b29-9fd9-3e6ce1032182) All these files are shown fine by the Lyric Show 3. I even removed all the possible Internet sources so that there is no Chinese interference, but it’s not that either. What is the problem ?

thank you so much, this worked perfectly for me
