### ISSUE TITLE
Remove synced lyrics if you manually save unsynced lyrics

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/foo_openlyrics#155]
To repro: Save synced lyrics for a track, then do a manual search to find some unsynced lyrics and hit ok/apply (check the Console to see that it does actually save). See that the visible lyrics update to the unsynced lyrics, but if you search again it'll still find the previously-saved synced lyrics.

EDIT: Or at least ask if the user would like to do this (with a note that search will prefer the synced lyrics)

**Comment by Rexadev** [comment]
But Unsynced and synced have separate fields what is the point

**Comment by Rexadev** [comment]
1. Unsynced and synced have separate fields.
2. what is the point?
3. I use save both.
4. Automatically deleting is counter intuitive
5. Add option to turn auto delete off

@jacquesh

**Comment by jacquesh** [comment]
This can instead be achieved by selecting the wrong local file from a manual search and then using the "Delete current lyrics" edit and searching again.
