### ISSUE TITLE
Prefer field of metadata in order specified

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#161]
![image](https://user-images.githubusercontent.com/62152714/185583462-23941874-6090-46e7-88d3-3136e0de93c0.png)

When Lyrics are in both Lyrics and SyncedLyrics it plays Lyrics

Some time it prefers SyncedLyrics too

~Maybe for flac and mp3 it prefers SyncedLyrics and for opus Lyrics~

**Comment by jacquesh** [comment]
Can you please:
* Enable debug logging (on the "Display" preferences page)
* Open the console (menu bar -> View -> Console)
* Clear the console (the "Clear" button in the bottom-left)
* Play the track that has lyrics stored in both the "Lyrics" and "SyncedLyrics" tags
* Check that it loaded the lyrics from "Lyrics"
* Copy the contents of the log and paste it here

(and then you can disable debug logging again afterwards)

**Comment by Rexadev** [comment]
Opening track for playback: "Path\Bow Chicka Wow Wow.opus"
INFO-OpenLyrics: ID3 tag artist appears multiple times for /Mike Posner/Bow Chicka Wow Wow/Bow Chicka Wow Wow. Only the first value will be used of: /Mike Posner/Lil' Wayne.
INFO-OpenLyrics: Failed to read search-avoidance info: Unsupported format or corrupted file
INFO-OpenLyrics: ID3 tag artist appears multiple times for /Mike Posner/Bow Chicka Wow Wow/Bow Chicka Wow Wow. Only the first value will be used of: /Mike Posner/Lil' Wayne.
INFO-OpenLyrics: Searching for lyrics for artist='Mike Posner', album='Bow Chicka Wow Wow', title='Bow Chicka Wow Wow'...
INFO-OpenLyrics: Save file name format '[%filename%]' with directory class 'TrackFileDirectory' evaluated to 'file://Path\Bow Chicka Wow Wow'
INFO-OpenLyrics: Querying for lyrics in file://Path\Bow Chicka Wow Wow.lrc...
INFO-OpenLyrics: Querying for lyrics in file://Path\Bow Chicka Wow Wow.txt...
INFO-OpenLyrics: Found 0 lyrics in local files: file://Path\Bow Chicka Wow Wow
INFO-OpenLyrics: Failed to retrieve lyrics from source: Local files
INFO-OpenLyrics: ID3 tag artist appears multiple times for /Mike Posner/Bow Chicka Wow Wow/Bow Chicka Wow Wow. Only the first value will be used of: /Mike Posner/Lil' Wayne.
INFO-OpenLyrics: Searching for lyrics in tag: SYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: LYRICS
INFO-OpenLyrics: ID3 tag artist appears multiple times for /Mike Posner/Bow Chicka Wow Wow/Bow Chicka Wow Wow. Only the first value will be used of: /Mike Posner/Lil' Wayne.
INFO-OpenLyrics: Found lyrics in tag: LYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCEDLYRICS
INFO-OpenLyrics: Searching for lyrics in tag: UNSYNCED LYRICS
INFO-OpenLyrics: Successfully retrieved lyrics from source: Metadata tags
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Loaded lyrics already form a valid UTF-8 sequence
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: ID3 tag artist appears multiple times for /Mike Posner/Bow Chicka Wow Wow/Bow Chicka Wow Wow. Only the first value will be used of: /Mike Posner/Lil' Wayne.
INFO-OpenLyrics: Lyric loading complete
INFO-OpenLyrics: ID3 tag artist appears multiple times for /Mike Posner/Bow Chicka Wow Wow/Bow Chicka Wow Wow. Only the first value will be used of: /Mike Posner/Lil' Wayne.

**Comment by jacquesh** [comment]
That is working. There are no lyrics in "SYNCEDLYRICS". So it uses those in "LYRICS".

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/185804710-208dba52-40f0-4568-8fe8-92d7691a0c98.png)

@jacquesh

**Comment by jacquesh** [comment]
O_o that's...very strange. The code is literally just "do we have a tag? Then collect the data it contains. Did we get any text? If yes then use that". There *seemingly* isn't a whole lot of room for it to go wrong.

I'll have to try reproduce it locally.

**Comment by jacquesh** [comment]
@Rexadev is this still happening for you? I can't reproduce this locally =/

I've setup the same tag search sequence and tag contents shown in your screenshots and on my end it does manage to find lyrics in the SYNCEDLYRICS tag.

**Comment by Rexadev** [comment]
It doesn't happen now. I checked a lot of songs
@jacquesh
