### ISSUE TITLE
Show Lyrics in "Search for Lyrics" box in order specified in Preferences/Search Order 

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#162]
put line to separate sources
Show Icon with Source name or Tint the background with the icon

**Comment by jacquesh** [comment]
No.

The manual search window is populated as we get results from the various sources. Keeping them in sorted order would add very minimal value (you can already sort by the source column if you want them grouped together but they aren't originally) and adding them to anywhere other than the bottom of the list would cause items to move on the list, making it more difficult to select the one you want.

Similarly I'm not adding icons or colouration to the list. You can read the "Source" column.

I don't know what you mean by "put line to separate sources".
