### ISSUE TITLE
Preference [Small]Add option to not use Album when Searching

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#164]
Most of the times removing album from search works specially for musixmatch

For Auto Search Fallback to without album
For Manual Search add option in settings to automatically search without it

**Comment by jacquesh** [comment]
I've not experienced this very much (once or twice when my album tags include "[Special Edition]" or something). Also the lack of others reporting the same issue suggests its not "most of the time".

Also there's always manual search so I'm reluctant to do this.

**Comment by Rexadev** [comment]
> Also the lack of others reporting the same issue suggests its not "most of the time".

It can be discussed.

https://www.reddit.com/r/foobar2000/comments/wy3q61/foo_openlyrics_if_you_find_searching_without/
