### ISSUE TITLE
Add option to switch of SyncedLyrics syncing

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#166]
Sometimes when SyncedLyrics are Off it will be easier to switch off syncing instead of setting offset.
This will also eliminate the need to save both synced and UnSyncedLyrics

**Comment by jacquesh** [comment]
There is already a "Remove timestamps" auto-edit that will achieve this. Why do you want both synced and unsynced lyrics?

**Comment by Rexadev** [comment]
> There is already a "Remove timestamps" auto-edit that will achieve this. 
Not Remove more Like On/Off Toggle

>Why do you want both synced and unsynced lyrics?
Sometimes when SyncedLyrics are Off it will be easier to switch off syncing instead of setting offset.

**Comment by jacquesh** [comment]
> Not Remove more Like On/Off Toggle

I see no reason why you would want this. Either you're content with the timestamps (in which case you're done) or you're not but you're willing to fix them (which is *very* little effort if the only thing you need to do is set the offset) or you're not and you're not willing to fix them (in which case there is no reason not to delete them or remove their timestamps).

I'm open to suggestions for making it easier to set the offset (as far as I can tell the only reasonable avenue for that is hotkeys in the editor, which I'd like to do anyway), but without better justification I'm not adding the option to temporarily disable them for a single track.

**Comment by Rexadev** [comment]
@jacquesh 

Most of the times automatically selected lyrics are offset turning-off synced-lyrics time-sync if a quick solution.
