### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#168]

**Comment by jacquesh** [comment]
I've been meaning to add this to the issue template for a little while but hadn't gotten round to it until now:
> If you'd like a new lyric source to be added, you must provide at least one example per source of a track whose lyrics are available on the new source but are not available on any existing sources. Each example must include an artist & track name, and must include an album name if it is part of an album. Album versions of tracks are preferred. If your example only applies to for a particular non-album version of a track (e.g a live or acoustic version), it may be disregarded.

Please can you update your issue accordingly

**Comment by Rexadev** [comment]
>  whose lyrics are available on the new source but are not available on any existing sources

Is that necessary ? There can be other reasons to add new source. For synced lyrics There can a better synced version. For UnSynced there can be a more official source or have more details like background vocals.

**Comment by jacquesh** [comment]
Well then post an example of that :)

The point of having requirements like this is that I have very limited time & energy to volunteer for work on openlyrics. There is one of me and many of you (the users), if I can reduce the amount of time I have to (or feel compelled to) spend on each suggestion in exchange for increasing the amount of time it takes for users to make suggestions then I'll take that trade-off every day of the week.

It also helps give some more information about how useful a given change would be, both to the person suggesting it and everybody else, which is important for prioritising which improvements to work on. On top of that, every time a feature is added, it becomes a little more difficult to add all future features (by virtue of the software being more complex overall). This is admittedly less true for sources than for other features but still applies.

Finally, to be honest, adding sources is not particularly high on my priority list in general, but that may change and it still helps regardless.

**Comment by Rexadev** [comment]
>Well then post an example of that :)

https://github.com/jacquesh/foo_openlyrics/issues/169
