### ISSUE TITLE
Musixmatch Lyrics available but not showing

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#174]
https://www.musixmatch.com/lyrics/Lana-Del-Rey/Venice-Bitch
![image](https://user-images.githubusercontent.com/62152714/186871531-0a8b172c-1fc2-47c3-be9b-777cd3895e6c.png)

---------------

#### Steps to reproduce
1.
2.
3.

#### Versions

* foobar2000 version:
* OpenLyrics version:

**Comment by jacquesh** [comment]
Works for me today, could have been an ephemeral issue with musixmatch or your connection to it. Pending more info I'm closing this as fixed.

**Comment by jacquesh** [comment]
Scratch that, I found a bug that would *sometimes* (randomly) cause results to not show in the list, while investigating #180. Should be fixed in the next release.
