### ISSUE TITLE
genius.com Lyrics available but not showing

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#180]
![image](https://user-images.githubusercontent.com/62152714/187076194-a9554ab7-dd83-4cca-9df3-e7357d7a384f.png)
![image](https://user-images.githubusercontent.com/62152714/187076208-910e9cad-a2fc-4256-8c5c-438d8cea2996.png)
![image](https://user-images.githubusercontent.com/62152714/187076307-2a419121-e1da-45cf-9362-9600b7efb86f.png)

https://genius.com/Original-broadway-cast-of-hamilton-and-renee-elise-goldsberry-satisfied-lyrics

For this song - azlyrics and MusixMatch too doesn't show - 
https://www.azlyrics.com/lyrics/linmanuelmiranda/satisfied.html
https://www.musixmatch.com/lyrics/Renee-Elise-Goldsberry-Original-Broadway-Cast-of-Hamilton/Satisfied

---------------------------------------------

#### Steps to reproduce
1.
2.
3.

#### Versions

* foobar2000 version:
* OpenLyrics version:

**Comment by Rexadev** [comment]
@jacquesh not fixed, for this song at least.

**Comment by Rexadev** [comment]
> @jacquesh ~not fixed, for this song at least.~ Album and Artist has to be exact maybe that is Genius API problem.
> 
> Had to use-
> 
> 1. Original Broadway Cast of “Hamilton” & Renée Elise Goldsberry
> 2. Hamilton: An American Musical (Original Broadway Cast Recording)
> 
> This Doesn't work-
> 
> 1. `Renée Elise Goldsberry
> 2. Hamilton`

@jacquesh you saw this ?

**Comment by jacquesh** [comment]
I did. You figured out that Genius generally only works if your tags are exactly correct (or rather, exactly match what Genius expects). This is not a bug, that's just how it works.
