### ISSUE TITLE
Add option to mark a song as Intrumental

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#181]
> - How you think the new feature/improvement would be helpful, or what problem you think it would solve.

Tell user and openlyrics to not search for lyrics
User can now search their library using LANGUAGE IS Instrumental.

By adding value Instrumental to LANGUAGE (TLA,TLAN) and LYRICS,SYNCEDLYRICS (USLT,TXT,SLT,SYLT) fields.
If a song fails to search for lyrics and user notices if it is a Instrumental song. They can then right click and Mark it as Instrumental.

EDIT: Muixmatch also have this info https://www.musixmatch.com/lyrics/Polyphia/G-O-A-T

**Comment by jacquesh** [comment]
Please use the templates I've setup for features and bug requests. They were created for a reason and I have explained this to you already. If you continue to blatantly ignore the templates you will be blocked from the repo.

You can already mark a track as instrumental and OpenLyrics will not download lyrics for these tracks and will show its own text instead. It currently does not store this information on the track (see the discussion in #129). I would, however, be willing to make it set some non-lyric metadata field (such as language) if there is precedent to do so. Can you provide any evidence that this is a common or official use of that field?

**Comment by Rexadev** [comment]
> Can you provide any evidence that this is a common or official use of that field?

LANGUAGE field - MARC Code zxx is used to tell no linguistic context (https://www.musiclibraryassoc.org/mpage/mdr_IIIF)

Why not also add it to LYRICS field?

**Comment by Rexadev** [comment]
> Please use the templates I've setup for features and bug requests. 

Updated

> If you continue to blatantly ignore the templates you will be blocked from the repo.

That is rude I am contributing to the project

> You can already mark a track as instrumental and OpenLyrics will not download lyrics for these tracks and will show its own text instead. It currently does not store this information on the track (see the discussion in https://github.com/jacquesh/foo_openlyrics/issues/129). I would, however, be willing to make it set some non-lyric metadata field (such as language) if there is precedent to do so.

Why not add it in LYRICS field too.

> Can you provide any evidence that this is a common or official use of that field?

LANGUAGE field - MARC Code zxx is used to tell no linguistic context (https://www.musiclibraryassoc.org/mpage/mdr_IIIF)

**Comment by jacquesh** [comment]
> That is rude I am contributing to the project

I don't think I'm being rude. I'm trying to setup processes to protect my time and I want people to at least put a little effort into following them. If they do not I need to take some action otherwise what was the point of setting up the processes to begin with? I value your bug reports and feature requests when they've been thought through, fit the project and add significant value but between the large quantity of feature requests you make and the small amount of explanation given for most of them, it sometimes feels as if you're being rather spammy. I'm sure that's not your intention, I'm just saying that that is how it comes across sometimes. Making essentially the same post 5 days apart and tagging me in the second one (presumably in an effort to get my attention) is another example of this. Please do not do that, I saw your first post.

> Why not add it in LYRICS field too.

Because it's not lyrics. I have yet to be convinced that I should use lyric storage to store "There are no lyrics".

**Comment by Rexadev** [comment]
> Because it's not lyrics. I have yet to be convinced that I should use lyric storage to store "There are no lyrics".

1. It is show user that the song is instrument and they will not wait for lyrics to load
2. Tell user and openlyrics to not search for lyrics

**Comment by Rexadev** [comment]
@jacquesh More people are interested in Mark as Instrumental behavior
https://www.reddit.com/r/foobar2000/comments/y35b04/comment/is7aevb/?context=3

Maybe be if you post you self more people will give thier opinion. Not everyone has GitHub

**Comment by jacquesh** [comment]
This would actually be covered by #202 (you can configure whatever filter you link to skip instrumental tracks). It wouldn't set any particular tags on the track, but at least openlyrics would behave in the desired fashion and each user can configure the exact set of conditions that they'd like to use to automatically skip lyric searches (which I'm taking as roughly-equivalent to considering the track to be instrumental).

**Comment by Rexadev** [comment]
> This would actually be covered by #202 (you can configure whatever filter you link to skip instrumental tracks). It wouldn't set any particular tags on the track, but at least openlyrics would behave in the desired fashion and each user can configure the exact set of conditions that they'd like to use to automatically skip lyric searches (which I'm taking as roughly-equivalent to considering the track to be instrumental).

Users are locked in f2k-openlyrics environment locked.
People use f2k to manage metadata.
People listen on many devices.
people share files with others.
People use f2k as server DLNA.
