### ISSUE TITLE
Foobar2000 2.0 / 64bit Support

### ISSUE THREAD

**Issue by swiffer** [jacquesh/foo_openlyrics#183]
Would be great to see a recompiled version using the latest version of the extension sdk to allow it to run on 64bit / with foobar2000 2.0 beta 2.

https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Development:SDK_2022-08-10_Release_Notes

**Comment by jacquesh** [comment]
Oh awesome, I hadn't heard about 64-bit support yet. Thanks for mentioning it!

I'll get this in for the next release.

**Comment by Rexadev** [comment]
When using the current verion in fb2k v2 beta 3 fields are fliped
![image](https://user-images.githubusercontent.com/62152714/188272277-d75fbf87-e265-4f49-a415-cffa32a1af76.png)

**Comment by rusegithub** [comment]
> Oh awesome, I hadn't heard about 64-bit support yet. Thanks for mentioning it!
> 
> I'll get this in for the next release.

I guess this will be the solution to this ...

`Could not load component "foo_openlyrics-v1.2.fb2k-component": This component was built for a different processor architecture.`

Looking forward to it, thanks.
