### ISSUE TITLE
Editor font size

### ISSUE THREAD

**Issue by lollita** [jacquesh/foo_openlyrics#184]
Do it is possible to add a option to customize editor font size?
I prefer a broken line to eye effort.

**Comment by jacquesh** [comment]
Maybe, but the editor uses the same font size used everywhere else in the fb2k UI, why is the editor materially different to the preferences window, or the playlist view?

> I prefer a broken line to eye effort.

I don't understand what you mean by this.

**Comment by lollita** [comment]
I prefer A line of text truncated because with a large character to red eyes for tiredness.

**Comment by jacquesh** [comment]
You can set the default font (including size) at Preferences/Display/Default User Interface/Colors and Fonts/Default but I see the editor doesn't use that. Yeah that can added.
