### ISSUE TITLE
Add option to add date to lyrics

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#189]
- How you think the new feature/improvement would be helpful, or what problem you think it would solve

After some time lyrics get improved move accurate, better formatting especially for songs release 1 year ago.

This song was released in 2016 was in billlboard hot 100 year end and still gets better formatting just 2 weeks after I download it lyrics.
 
shocking is now shockin'
![image](https://user-images.githubusercontent.com/62152714/189666883-94d6dfc6-5957-417f-8895-2870766c3ecb.png)
![image](https://user-images.githubusercontent.com/62152714/189666897-35097891-3e53-4c4b-974f-b6d2990da163.png)

**Comment by jacquesh** [comment]
Do you mean you'd want to see for each source when those lyrics were last updated? That seems unlikely to be possible because it relies entirely on sources providing this info.

**Comment by Rexadev** [comment]
> Do you mean you'd want to see for each source when those lyrics were last updated? That seems unlikely to be possible because it relies entirely on sources providing this info.

Date the lyrics were downloaded.

**Comment by jacquesh** [comment]
Downloaded date is something we can do, but that wouldn't tell you whether the lyrics you have are behind what the remote source has. Where do you anticipate this would be shown? Can you given an example of what you'd like to see?

**Comment by Rexadev** [comment]
> that wouldn't tell you whether the lyrics you have are behind what the remote source has.

Can you add option to compare automatically or manually?

> Where do you anticipate this would be shown? Can you given an example of what you'd like to see?

At the end or start of lyrics where source is being planned to put. If you put date you need to put source.

**Comment by jacquesh** [comment]
Added a mention of showing a timestamp to lyrics info displayed in #52

**Comment by Rexadev** [comment]
@jacquesh would you reconsider ?

**Comment by jacquesh** [comment]
What do you want me to reconsider?

In general we have no way of knowing when last a particular lyric was updated on a remote source and I've already linked to an issue where we could store the date when local lyrics were retrieved.

**Comment by Rexadev** [comment]
@jacquesh also add date. related to https://github.com/jacquesh/foo_openlyrics/commit/b99f3163e5c99be7792fcbbb3438561d3d2fdc52

**Comment by Rexadev** [comment]
@jacquesh is it completed by b99f316

**Comment by jacquesh** [comment]
That commit adds info about when the lyrics were first/last retrieved and when they were last edited locally, but as I said above, we have no way of knowing in general when the lyrics on a remote source were last modified.

**Comment by Rexadev** [comment]
> That commit adds info about when the lyrics were first/last retrieved and when they were last edited locally, but as I said above, we have no way of knowing in general when the lyrics on a remote source were last modified.

That metadata is store in foobar2000 not in file ? I would like it better inside lyrics

**Comment by Rexadev** [comment]
@jacquesh you may close this issue
