### ISSUE TITLE
ctrl+A  not working in Lyric Editor

### ISSUE THREAD

**Issue by pcm8081** [jacquesh/foo_openlyrics#190]
#### Steps to reproduce
1.when we presss ctrl + A  then nothing happend
2.os >windows 8.1 Pro
3. well working in windows 10 
4. video is given below for [proof](url)

#### Versions

https://user-images.githubusercontent.com/100966712/190586574-7ef4cbac-2304-4fa6-9394-e584a65a8b0b.mp4

* foobar2000 version:
* OpenLyrics version:

**Comment by jacquesh** [comment]
It's just a standard windows text box. =/

Does the same apply for other text boxes around fb2k? Does the same apply for older versions? etc.

**Comment by pcm8081** [comment]
Problem create  for cut /copy/ paste
 when not select all  by pressing Ctrl+A
