### ISSUE TITLE
Add an option to seek through lyrics

### ISSUE THREAD

**Issue by DiscordTraveller** [jacquesh/foo_openlyrics#191]
Add an option to seek through the lyrics, i.e., drag the lyrics up/down and have the song playback from there, really useful feature I can't find on this plugin.

This of course wouldn't work with unsynced lyrics.

**Comment by jacquesh** [comment]
Duplicate of #179

**Comment by DiscordTraveller** [comment]
> Duplicate of #179

Thank you for the quick reply, here's a clip showcasing the idea.

https://user-images.githubusercontent.com/94841148/192109483-130f64a2-80ed-41d5-b408-c18770bc1a55.mp4
