### ISSUE TITLE
Lyrics+Chords

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#197]
> How you think the new feature/improvement would be helpful, or what problem you think it would solve

For musicians it is nice to get chords quickly.

----
Format - https://en.wikipedia.org/wiki/ChordPro

Example - https://tabs.ultimate-guitar.com/tab/ed-sheeran/perfect-chords-1956589

This would need a ablity to have Lyrics is one panel and Lyrics+Chords in another. Also separate preferences for each.

Need Monospace font or whatever the font that website is using.

Parse Capo - This is, if Capo is 1st fret on Guitar (on other fretted instrument like ukulele). C chord becomes C#, C# becomes D
[Chromatic_scale](https://en.wikipedia.org/wiki/Chromatic_scale)
https://github.com/Open-SL/Chords-Transposer

Sources -
https://github.com/elainewlin/MusicParsed [FOSS Database]
https://www.e-chords.com/chords/taylor-swift/lover
https://chordseasy.com/song/27422/lover/Buisyguitar
https://www.yourguitarsuccess.com/lover-chords/

### If you really like the idea

https://github.com/search?q=parse+chords
https://github.com/Arkham/elm-chords

--------------------------

Difficulty:intermediate
Tuning:[E A D G B E](https://www.ultimate-guitar.com/tools/tuner?tuning=E%20A%20D%20G%20B%20E)
Key:Ab
Capo:1st fret

**Comment by jacquesh** [comment]
This is definitely beyond the scope of openlyrics. We're a lyrics plugin, not a chord plugin. I can see the use-case, but it would make a lot more sense if this were in a separate plugin.
