### ISSUE TITLE
Add option to get translation for the lyrics

### ISSUE THREAD

**Issue by Arthurfogo7** [jacquesh/foo_openlyrics#199]
<!-- Please give a detailed description of the desired improvement here
Be sure to include at least:
- It would help people who don't know the language in which the song is, spotify does something similar but only a few songs have this feature

-Deepl, google translator or bing would work just fine, but I think this feature would improve a lot the experience using this

Thank you in advance

**Comment by jacquesh** [comment]
Dupe of #200
