### ISSUE TITLE
Skip filter

### ISSUE THREAD

**Issue by regorxxx** [jacquesh/foo_openlyrics#202]
Essentially, mimic the search filtering on lyrics show 3, which allows to bypass lyrics searching using a TF expression (on match).

![image](https://user-images.githubusercontent.com/83307074/196010190-6cab6a9e-07e0-445d-a6e8-af25a51a73c8.png)

Currently there is a "mark as instrumental" option, but that could be automatized this way too (it's not practical to mark large libraries of instrumental tracks). 

For ex. when a track is already marked as 'instrumental' with a tag (genre) or for 'jazz' tracks (but not 'vocal jazz'), on Lyrics 3.

**Comment by jacquesh** [comment]
@regorxxx Thanks for forwarding the request, but if I'm understanding correctly, is that not covered by #57 rather than this ticket? IE that user wants to make swap out the "we don't have any lyrics" text with just an empty string/panel?

**Comment by regorxxx** [comment]
I simplified my comment, it's both. You need some kind of identifier to filter "instrumental" tracks, that's this issue: have a query to skip lyric-fetching automatically according to track's tags.

Then, you are right, #57 would be the fallback to display in case lyric-fetching is disabled and/or no lyrics are available.

Therefore one request naturally fits with the other. But note #57 alone would not suffice, since there is still no way to automatically mark tracks as "instrumental" and avoid lyric fetching for them (and many times instrumental tracks have lyrics on servers, with just the title and some credits).

**Comment by Gggggas** [comment]
Hello, 

 Can we have the option to save lyrics in LRC format? 

Thank you :)

**Comment by sbrl** [comment]
Hello,

This might be a stupid question, but what solution was actually implemented for this? I've tried looking through issues, at documentation, reading release notes, and even taking a read of the code - but I can't seem to determine e.g. what id3/exif/etc tag I need to set to convince osdlyrics to see a given track as an instrumental track.

**Comment by jacquesh** [comment]
This is configured via titleformat under Preferences -> Tools -> OpenLyrics -> Searching (see the "Skip filter" section on that page)
