### ISSUE TITLE
Add QQ music support for lyric retrieval

### ISSUE THREAD

**Issue by snowbie** [jacquesh/foo_openlyrics#21]
[foo_qqmusiclyricssource.zip](https://github.com/jacquesh/foo_openlyrics/files/6643100/foo_qqmusiclyricssource.zip)

I've decompiled the dlls of the QQ lyric finder for LyricShowPanel3 if it helps provide the necessary information needed for lyric retrieval. I was going to to merge it myself, but it's structured too differently  for me to convert it 1:1 for openlyrics. With QQ support I can finally remove LyricShow3 altogether.

**Comment by veksha** [comment]
hi, @snowbie what tool you used to "decompile" my dlls? i think this decompilation contains no human readable code.
for qq lyrics implementation just look here [qqmusic_plus.js](https://github.com/Robotxm/ESLyric-LyricsSource/blob/master/qqmusic_plus.js)

**Comment by snowbie** [comment]
> 
> 
> hi, @snowbie what tool you used to "decompile" my dlls? i think this decompilation contains no human readable code.
> for qq lyrics implementation just look here [qqmusic_plus.js](https://github.com/Robotxm/ESLyric-LyricsSource/blob/master/qqmusic_plus.js)

ah, those were by you? Apologies. I had difficulty finding the source because I had originally grabbed the foobar component off of a forum, and googling never led me to the github page.
The software is strictly for decompiling [dlls to c](https://www.dll-decompiler.com/dll2c.html), so evidently that's where the problem lies as your plugin was written in js.

While I never thought the code itself would be usable, I assumed whatever pieces of code that called certain hex values could've viable.

**Comment by jacquesh** [comment]
Indeed that decompilation is not helpful. Points for effort though :)

Support for QQMusic has been on my TODO list for ages, it's just a matter of having the time and motivation to put in the work.

Having a reference is super helpful though, thanks @veksha! I had previously resorted to checking wireshark traces in an effort to reverse-engineer existing plugins >_<
