### ISSUE TITLE
When auto save off: Bulk download makes no sense.

### ISSUE THREAD

**Issue by tortuosit** [jacquesh/foo_openlyrics#210]
Hi guys, as reported in https://hydrogenaud.io/index.php/topic,120812.msg1018044.html#msg1018044

When I set the options to NOT auto save...
Now express my wish to manually bulk download lyrics - it does do that, but it was for nothing, because it is nowhere applied. When visiting one of those tracks, it just again downloads lyrics for it.

#### Steps to reproduce
1. Set Auto save off in options
2. Bulk download lyrics
3. A waste of time, they won't get applied

#### Expected behavior
IMO when I explicitely say "Search for lyrics" on multiple tracks, it should save the lyrics to the desired place (depending on the settings).

#### Versions
* foobar2000 version: 2 beta 12
* OpenLyrics version: 1.3

**Comment by jacquesh** [comment]
Fixed by 097da6b2f (although I referenced the wrong issue number)
