### ISSUE TITLE
Option for minimum characters

### ISSUE THREAD

**Issue by th-bu** [jacquesh/foo_openlyrics#213]
Can we get an option for specifying a minimum character length of the lyrics?

Especially NetEase has so many synced "lyrics" that only consist of the names of the writers. But since those are synced they prevent a real unsynced lyric file from being downloaded.

So the idea would be that I can set a minimum character length to a value, let's say 200 characters, and OpenLyrics ignores files that are shorter than that.

**Comment by jacquesh** [comment]
This would be covered by implementing #423 and then do the usual filtering for "empty lyrics get ignored"
