### ISSUE TITLE
Search and Show Results in Order specified in preferences.

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#220]
- How you think the new feature/improvement would be helpful, or what problem you think it would solve

Good for muscle memory.
Generally if user has Source 1, Source 2, Source 3 it is in the order of relevance.

**Comment by jacquesh** [comment]
I'd be willing to support sorting the manual search result list by column (which I seem to recall was suggested elsewhere but I can't find a ticket for it now, feel free to create one), and if so I can see an argument for remembering the sort order for future searches, but I'm not going to add an option for configuring a specific (custom) source-based display order.

**Comment by Rexadev** [comment]
> but I'm not going to add an option for configuring a specific (custom) source-based display order.

Use the same order as used in preference for sources to search

You said you will search disabled sources in manual search that's ok. So I am saying to search sources in order the user puts them.

and display them in the same order because
1. good for muscle memory
2. search results will not keep jumping


@jacquesh
