### ISSUE TITLE
"Search for lyrics" finds UnsyncedLyrics in metadata when set to search MusixMatch

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#221]
#### Steps to reproduce
1. Set preferences to only use MusixMatch
2. RightClick>Search for lyrics
3. The box will say "Found" even if the lyrics are in Metadata( are unsynced)

#### Versions

* foobar2000 version:
* OpenLyrics version:

**Comment by jacquesh** [comment]
I don't see a problem here and you've provided no expected behaviour.

As far as I can tell, your problem is that MusixMatch is returning unsynced lyrics, but that's a perfectly valid outcome.

**Comment by Rexadev** [comment]
Add option to search for "Synced Lyrics"

Sorry forgot to add it

@jacquesh

**Comment by Rexadev** [comment]
@jacquesh please reconsider this feature maybe I didn't explain it well before
