### ISSUE TITLE
v2 Fields Flipped

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#230]
### V2 Beta 14
![image](https://user-images.githubusercontent.com/62152714/204984418-46fa14be-602c-41f0-9b72-78830fa2835e.png)

### V1.6.14
![image](https://user-images.githubusercontent.com/62152714/204982486-0919f01b-eb19-4138-a1f8-f68754361696.png)

#### Steps to reproduce
1.
2.
3.

#### Versions

* foobar2000 version:
* OpenLyrics version:

**Comment by jacquesh** [comment]
This...seems unlikely.

As usual, you have neglected to fill in the information requested by the template. Please confirm that you are using the same version of openlyrics in fb2k v1.6.14 as in v2 beta 14, and which version that is. Closing until then.

**Comment by Rexadev** [comment]
@jacquesh Yes I am using openlyrics v1.6.14 in f2k v2 beta 14
