### ISSUE TITLE
Lyrics Doesn't Display Properly

### ISSUE THREAD

**Issue by christantoan** [jacquesh/foo_openlyrics#232]
Hello,

I'm planning to migrate from MiniLyrics and foo_uie_lyrics3 to OpenLyrics however I found out that none of my lyrics files are decoded correctly (jumbled text).

Left is OpenLyrics, middle is foo_uie_lyrics3, and right is MiniLyrics:
![image](https://user-images.githubusercontent.com/7300310/208706917-6bd1418f-bc98-4f9a-9407-66760ebdb233.png)
This is what's shown on Lyrics Editor window:
![image](https://user-images.githubusercontent.com/7300310/208707347-187918cf-6272-4a75-81a1-b8148a21fe0d.png)

#### Steps to reproduce
1. Play a music file with the lyric file located in the same folder named %filename%.lrc

#### Expected behavior

The lyrics of the song from the lyrics file are displayed with highlights at the right vocal.

#### Versions

* foobar2000 version: 1.6.14
* OpenLyrics version: 1.4

#### Additional information

Log file: [log.log](https://github.com/jacquesh/foo_openlyrics/files/10269997/log.log)
Example lyrics file: [8. Death Stranding.zip](https://github.com/jacquesh/foo_openlyrics/files/10269943/8.Death.Stranding.zip)

Hope this can be fixed. Thank you.

**Comment by christantoan** [comment]
Another type(?) of display issue but this time foo_uie_lyrics3 also fails to display the lyrics correctly while MiniLyrics does.
![image](https://user-images.githubusercontent.com/7300310/208711557-470add04-a57a-413f-98b0-f4395e9f1abe.png)

Logs: [log.log](https://github.com/jacquesh/foo_openlyrics/files/10270083/log.log)
Lyrics file: [1. Komatsu Mikako - Owaranai Melody wo Utaidashimashita.zip](https://github.com/jacquesh/foo_openlyrics/files/10270104/1.Komatsu.Mikako.-.Owaranai.Melody.wo.Utaidashimashita.zip)

**Comment by jacquesh** [comment]
Yeah that's a bug in the code for reading in lyrics. The Death Stranding file you gave is stored as UTF-16 and openlyrics doesn't recognise that correctly when it loads (because it hits a null byte and stops reading the string, for future-me or anybody else who might be interested).

I'll try get this fixed for the next version, but as a temporary workaround, if you could convert that to being stored as UTF-8 instead (some text editors allow you to set the encoding when you save), that should fix it for these lyrics.

**Comment by christantoan** [comment]
> if you could convert that to being stored as UTF-8 instead (some text editors allow you to set the encoding when you save), that should fix it for these lyrics.

Thanks! It works!

**Comment by jacquesh** [comment]
Oh woops, I didn't realise that was a completely different issue. That's the topic of #233

**Comment by christantoan** [comment]
> Oh woops, I didn't realise that was a completely different issue. That's the topic of #233

Ok. Sorry for reporting a different issue in one report :(, I didn't realize also that there's a topic of it already.
