### ISSUE TITLE
Add an Option to "fix" repeating lyrics

### ISSUE THREAD

**Issue by fetkitty** [jacquesh/foo_openlyrics#235]
Song lyrics that are repeated multiple times in a song are only written once in the .lrc file and use multiple time stamps infront of it to signal the fact that they are repeating, as shown in the attached image.
![Screenshot 2023-01-31 233627](https://user-images.githubusercontent.com/73826848/215899381-bcf36ae7-c89c-4426-9985-4c54eb9e3597.png)
This format isn't properly displayed on portable players, which only see the lines as appearing once in the song. 

Would it be possible to add a button that fixes the lyrics so that they are displayed chronologically instead? I hope this explanation was somewhat concise...

**Comment by jacquesh** [comment]
Uncheck the "Collapse multiple instances of the same line when saving timestamped lyrics" checkbox in the Saving settings. That should prevent saving lyrics with multiple timestamps per line like that.
You'll need to get it to re-save lyrics that already have lines grouped up like that though (play the track, open the lyric editor, click save).

**Comment by fetkitty** [comment]
Thanks for the quick reply! Looks like i missed that option - it works just how i wanted it to!
