### ISSUE TITLE
Gather some basic opt-in usage data

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/foo_openlyrics#237]
We can't keep adding features forever, it's not practical. In theory we could remove features (looking at you, horizontal scrolling), but this is always going to be at the risk of annoying users.

I don't actually have any idea how often the various features are used, so maybe I should add a very basic collection system that (when configured to do so...which will be *very* infrequently) we can use to prompt users asking them to please submit metrics and show them what it would send if they say yes. Also a server to process & store that data (can we leverage an existing service for this? Do we have any way of preventing it from being abused & flooded immediately)

**Comment by TFWol** [comment]
As long as it's Opt-In.

You could have a couple of toggle settings kind of like this:
```
   Section Header: "Help us improve by sharing lyrics options you use"
    - [X] Prompt me once in a while to send what lyrics options I use <--- on by default
    - [ ] "Automatically share favorite lyrics to inform future updates"
    - [ ] disable sending data
```
There could be a short description that mentions helping the developer. It would be best to emphasize that it will help determine what features will be removed that aren't being used.

For the prompt you could also maybe have the choice to send usage and/or click what options they use in some sort of mini poll, so you at least get some sort of data.
