### ISSUE TITLE
Suggestion for the "auto-edit lyrics" menu

### ISSUE THREAD

**Issue by beingalink** [jacquesh/foo_openlyrics#24]
As most lyrics from QQ display `&apos;` instead of `'`, I'd suggest to add an auto-replace option for that. Perhaps there are similar cases that could be covered this way. Thanks for your great component!

**Comment by jacquesh** [comment]
Good idea! Looking at [Wikipedia](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references) for reference, it should replace:
* `&amp;` -> `&`
* `&lt;` -> `<`
* `&gt;` -> `>`
* `&quot;` -> `"`
* `&apos;` -> `'`

**Comment by beingalink** [comment]
Perhaps "Replace named characters as used in XML/HTML"? It's a bit long though. You might also add such a replacement step before displaying and saving lyrics downloaded by your component. That would probably reduce the need for manual replacements in lots of cases.

**Comment by jacquesh** [comment]
I've added this auto-edit but I'm leaving the ability to have it run without any user intervention to a different issue (#25) because that applies to other edits too and for now at least there is the ability to have this fixed in 2 clicks rather than doing it manually.

**Comment by H2Swine** [comment]
I spent some attempts getting HTML entities replaced and was about filing it as a bug report until I read your comment as of 8th of July and found out that there wasn't more included. I have seen - admittedly I think that is in lyrics retrieved with an older component! - ampersand-encoded &auml;  &ouml; &uuml; &szlig; &aring; &aelig; &oslash; &oelig; (&amp;auml;  &amp;ouml; &amp;uuml; &amp;szlig; &amp;aring; &amp;aelig; &amp;oslahs; &amp;oelig) and a few more letters with diacritics like &ccedil; &amp;ccedil; . Plus guillemets &amp;laquo; &amp;raquo; and a few &amp;nbsp; 

I don't know the right way to file this? Open a new issue? And I guess it is a feature request and the only thing "bug" about it is that the description of the feature suggests more than it does.

**Comment by jacquesh** [comment]
@H2Swine yeah generally creating a new issue is the way to go, since its much easier to track what work is already done versus what still needs to be done. In this instance I've split your comment off into a new issue (#261) :)
