### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#241]
foobar2000 v2 has added ARM support

**Comment by jacquesh** [comment]
Does anybody actually run Windows on ARM though? :O

**Comment by marc2k3** [comment]
From the fb2k Beta 28 changelog...

- Supports ARM builds of components but doesn't actually require them, can transparently load x64 code.

Seems like there is no point at all.

I suppose it could be vaguely interesting for developers who have ARM hardware and want to play with new toys.

**Comment by jacquesh** [comment]
If the ARM fb2k can load x64 plugins then I'm not supporting a dedicated ARM build
