### ISSUE TITLE
Requests for 1.6

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#245]
Thanks for adding stream metadata lyrics retrieval in 1.5, which works FAST and accurately here!  Your option to remove bracketed expressions from search terms is welcome and provides hits with specific streams that other apps cannot.  A few requests:

1. Add option to turn off/on automatic retrieval
2. Add option to identify source of displayed lyrics at top of frame
3. Add additional lyrics sources: SongLyrics, Metal Archives, Deezer

Thanks again for such a smoothly operating 64-bit plugin for Foobar v2.

**Comment by jacquesh** [comment]
Thanks, I'm glad you like it :)

Deezer support was already requested in #157 and songlyrics in #151.

For the other requests, could you please open separate tickets for each? It's unlikely that all of them would get done at once and it's much, much easier to track progress if there are separate tickets for each feature/change :) Remember to please fill in a little bit of additional supporting info as indicated by the "feature request" template, which helps me understand the problem you're trying to solve with each request and if/how/where it fits in with the rest of openlyrics.
