### ISSUE TITLE
Add Feature to Change Offset

### ISSUE THREAD

**Issue by ngs428** [jacquesh/foo_openlyrics#252]
In LSP3 V0.5 you can right click on a loaded lyric and select "Adjust Offset".  Adjust as needed and hit save,  I don't see this feature in OpenLyrics.  I do like that you can apply the offset to the timestamps, that is a great help!  But being able to determine the offset in OpenLyrics would be great!

Adjust Offset Dialog Box
![Adjust Offset Dialog Box](https://user-images.githubusercontent.com/13911615/231168433-7e968efd-2474-4445-8248-22bc64bc68ed.png)

**Comment by jacquesh** [comment]
Is there any situation in which you know the exact offset (in milliseconds)?

You can already adjust the offset using the "Sync line using 'offset' tag in the lyric editor which I expect is a much more useful interface than requiring you to specify a number of milliseconds (although technically you can already do that by manually adding an `[offset:<number of milliseconds>]` tag to the top of your synced lyrics).

**Comment by ngs428** [comment]
The first step is to find the offset.  In LSP3 you start the song and then bring up that dialog box.  You then increase or decrease the offset and watch how the lyrics are then synched as the song plays.  Once you have the offset it is saved to the tag.

Then I typically use your tool to adjust all the time stamps by the offset.  I like this part about yours, but you need to find the offset first to use it.  So how I described in the first paragraph is how you find it.
________________________________

**Comment by jacquesh** [comment]
Sure but that sucks and is a painful manual process of trial-and-error. Is it not strictly better to use the existing "Sync line..." functionality I mentioned above to open the editor, click the button at the right point in time and now you're immediately done?

**Comment by ngs428** [comment]
I will give that a try.  It sounds better.
________________________________
