### ISSUE TITLE
Source suggestion: Metal Archives (and Bandcamp?)

### ISSUE THREAD

**Issue by H2Swine** [jacquesh/foo_openlyrics#253]
Metal Archives: 
- Examples that I don't find through the component: https://www.metal-archives.com/albums/Wormphlegm/In_an_Excruciating_Way_Infested_with_Vermin_and_Violated_by_Executioners_Who_Practise_Incendiarism_and_Desanctifying_the_Pious/32930 doesn't seem to be much available. https://www.metal-archives.com/albums/Denial_of_God/The_Ghouls_of_DOG/10278 and others from the same artist do at least fail a search. So did The Funeral Orchestra: Apocalyptic Trance Ritual, although I see that the M-A only has a couple of tracks from it. 
- For development: There is already a component for Lyric Show Panel 3, https://hydrogenaud.io/index.php/topic,108084.0.html . Also https://www.reddit.com/r/foobar2000/comments/o7ua73/lyric_show_panel_3_lyrics_from_genius_musixmatch/ 
- And more code - MIT licensed: https://github.com/noeldelgado/metallum
- addendum: it seems a certain authoritarian regime blocks the site, but try replace "www." by "cats." and it seems all fine. (Yes, [that April Fools' Day prank](https://loudwire.com/metal-archives-band-photos-cats/) has actually become a permanent thing.)

Bandcamp: Not so much because what might be available there and nowhere else, but: provided by the artist/label, so I guess they would be accurate. And might very well show up upon release, even.

**Comment by Rexadev** [comment]
```
#include <string>
#include <vector>
#include "HttpReader.h"
#include "LyricsSource.h"
#include "Util.h"

class MetalArchivesLyricsSource : public LyricsSource
{
public:
    MetalArchivesLyricsSource() {}
    virtual ~MetalArchivesLyricsSource() {}

    virtual const char *GetName() { return "Metal Archives"; }

    virtual bool GetLyrics(const char *artist, const char *title, std::vector<std::string> &lyrics)
    {
        std::string url = "https://www.metal-archives.com/search/ajax-advanced/searching/songs/?bandName=" + url_encode(artist) + "&songTitle=" + url_encode(title) + "&sEcho=1&iColumns=4&sColumns=&iDisplayStart=0&iDisplayLength=200&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&_=1619896351577";
        HttpReader reader(url.c_str());

        std::string response;
        if (!reader.GetResponse(response))
        {
            return false;
        }

        std::string id;
        if (!parse_metal_archives_song_id(response, id))
        {
            return false;
        }

        url = "https://www.metal-archives.com/release/ajax-view-lyrics/id/" + id;
        reader.SetUrl(url.c_str());

        response.clear();
        if (!reader.GetResponse(response))
        {
            return false;
        }

        lyrics.clear();
        parse_openlyrics(response, lyrics);

        return true;
    }

private:
    bool parse_metal_archives_song_id(const std::string &response, std::string &id)
    {
        std::string::size_type pos = response.find("tbody");
        if (pos == std::string::npos)
        {
            return false;
        }

        pos = response.find("songRow_", pos);
        if (pos == std::string::npos)
        {
            return false;
        }

        pos += 8;
        std::string::size_type end_pos = response.find("\"", pos);
        if (end_pos == std::string::npos)
        {
            return false;
        }

        id = response.substr(pos, end_pos - pos);

        return true;
    }
};

// Register the lyrics source
static RegisterLyricsSource<MetalArchivesLyricsSource> s_metal_archives_lyrics_source;

```

**Comment by Rexadev** [comment]
Bandcamp Duplicate https://github.com/jacquesh/foo_openlyrics/issues/82

**Comment by Rexadev** [comment]
```
#include <foobar2000.h>
#include <sources.h>
#include <httpclient.h>

class MetalArchivesLyricsSource : public lyrics_source {
public:
    bool get_lyrics(const file_info &info, abort_callback &abort, service_ptr_t<lyrics_result_receiver> p_receiver) override {
        // Extract artist and title from file_info
        const char* artist = info.meta_get("ARTIST", 0);
        const char* title = info.meta_get("TITLE", 0);
        
        // Build query URL
        std::string query_url = "https://www.metal-archives.com/search/ajax-artist-search/?field=name&query=" + std::string(artist) + "&sEcho=1&iColumns=4&iDisplayStart=0&iDisplayLength=200";
        
        // Send query to Metal Archives
        http_client::ptr client = http_client::create();
        http_request::ptr request = client->create_request("GET", query_url.c_str());
        http_response::ptr response = client->send_request(request, abort);
        
        // Parse response to find matching artist
        // ...
        
        // Build URL for artist page
        std::string artist_url = "https://www.metal-archives.com/band/view/id/" + std::to_string(artist_id);
        
        // Send request for artist page
        request = client->create_request("GET", artist_url.c_str());
        response = client->send_request(request, abort);
        
        // Parse response to find lyrics
        // ...
        
        // Send lyrics to receiver
        p_receiver->on_lyrics(artist, title, lyrics.c_str());
        
        return true;
    }
};

static const service_factory_single_t<MetalArchivesLyricsSource> g_MetalArchivesLyricsSource_factory;

```

**Comment by sveakul** [comment]
> Metal Archives:
> 
>     * Examples that I don't find through the component: https://www.metal-archives.com/albums/Wormphlegm/In_an_Excruciating_Way_Infested_with_Vermin_and_Violated_by_Executioners_Who_Practise_Incendiarism_and_Desanctifying_the_Pious/32930 doesn't seem to be much available. https://www.metal-archives.com/albums/Denial_of_God/The_Ghouls_of_DOG/10278 and others from the same artist do at least fail a search. So did The Funeral Orchestra: Apocalyptic Trance Ritual, although I see that the M-A only has a couple of tracks from it.
> 
>     * For development: There is already a component for Lyric Show Panel 3, https://hydrogenaud.io/index.php/topic,108084.0.html . Also https://www.reddit.com/r/foobar2000/comments/o7ua73/lyric_show_panel_3_lyrics_from_genius_musixmatch/
> 
>     * And more code - MIT licensed: https://github.com/noeldelgado/metallum
> 
>     * addendum: it seems a certain authoritarian regime blocks the site, but try replace "www." by "cats." and it seems all fine. (Yes, [that April Fools' Day prank](https://loudwire.com/metal-archives-band-photos-cats/) has actually become a permanent thing.)
> 
> 
> Bandcamp: Not so much because what might be available there and nowhere else, but: provided by the artist/label, so I guess they would be accurate. And might very well show up upon release, even.

Metal Archives currently has 167,299 bands, vs. the 4,500+[sic] for Dark Lyrics, according to each one's website.  I strongly support the addition of both MA and Bandcamp.

**Comment by jacquesh** [comment]
I've added metal-archives.com for the next release. Bandcamp is tracked by #82

**Comment by Rexadev** [comment]
> I've added metal-archives.com for the next release. Bandcamp is tracked by #82

Add option to only search on metalarchives when using auto-search when Genre tag has metal word in it

**Comment by Tenome** [comment]
I'm also interested in Metal Archives, so I await the next updated release.

**Comment by H2Swine** [comment]
Thanks for adding it. Now ... maybe this should be a more general issue: 
Metal Archives has a "lyrics not available" placeholder. If the component finds that string, the best would likely be to treat it as a _not found._ 
I guess other sources must have their own placeholders ... ?

**Comment by Rexadev** [comment]
Add option to only search on metalarchives when using auto-search when Genre tag has metal word in it @jacquesh

**Comment by jacquesh** [comment]
@H2Swine a quick test suggests this doesn't apply in all cases, but maybe just artists that they usually have lyrics for but don't for that particular track? Can you please open a new issue with as much detail as you have (rather than reviving old, already-completed issues) and I can see what would make the most sense.

**Comment by Rexadev** [comment]
Rename title to metal-archives.com
