### ISSUE TITLE
LRC offset is not applied by this plugin

### ISSUE THREAD

**Issue by puffpppp** [jacquesh/foo_openlyrics#257]
LRC files support the option to specify an offset for the lyrics like this:

[offset: -3000]
[ar: Noel Gallagher's High Flying Birds]
[ti: The Right Stuff]
[al: Chasing Yesterday]
[length: 05:25]
[id: 51037068]
[00:05.64]
[01:20.39]Out of the blue I heard an angel say
[01:25.93]Give me your soul and I'll be on my way
[01:31.10]You and I got the right stuff

This is not applied by the plugin thus any LRC files using this value show up as wrongly timed.

#### Steps to reproduce
You can replicate just by adding any random offset value as shown above, you will find that it has no effect on the lyrics shown.

#### Expected behavior
This value should be applied to all the timestamps, A negative value causes the lyrics to be shown delayed, ie they appear lagging, A positive value should cause them to appear sooner.

#### Versions
* foobar2000 version: v2.0 [x64]
* OpenLyrics version: 1.6

**Comment by puffpppp** [comment]
https://en.wikipedia.org/wiki/LRC_(file_format)

**Comment by jacquesh** [comment]
I just checked locally since this really should work: It appears having space between the colon and the offset number breaks it. As a workaround until I can fix this: Can you try remove the space (so that the offset line becomes `[offset:-3000]`? That seems to work for me.

**Comment by puffpppp** [comment]
That's right I removed the space from the tags and it works correctly now, thanks!
