### ISSUE TITLE
Skip search sources during bulk-search if they wouldn't produce any saved lyrics.

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/foo_openlyrics#263]
Bulk-search doesn't interact with the currently-playing/visible track and so the flow of "the auto-search found a result, you can choose if you want to save it" doesn't apply. So if we are doing a bulk search and are configured to only save synced lyrics then we should not even attempt to search a source that is known to never provide synced lyrics (for example).

This could potentially allow us to avoid many pointless requests to some sources (which reduces load on sources and by extension the chance that sites will rate-limit or block us). It does however, rely on us accurately tagging sources with info about what lyrics they provide. e.g Does musixmatch ever provide *unsynced* lyrics?

**Comment by H2Swine** [comment]
According to https://community.musixmatch.com/?lng=en and https://community.musixmatch.com/guidelines?lng=en#transcribe , lyrics can be contributed unsynced. 
(That is not an outright answer; it does not say definitely that lyrics can be published before they are synced.)

**Comment by H2Swine** [comment]
And today, 1.6 found an unsynced Musixmatch lyric for me.

**Comment by jacquesh** [comment]
Seems not particularly useful.
