### ISSUE TITLE
Musixmatch no longer returning hits

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#265]
#### Steps to reproduce
1. Remove all sources except for Musixmatch
2. Search for any title that does find results from Musixmatch on other apps
3. No hits

#### Expected behavior
Lyrics should be returned but are not, even though they ARE found at Musixmatch by Foobar 1.6.16 using LSP-3 and MultiSource, and by MusicBee using LyricsReloaded.

The Authentication Token in use is the same one that does produce results with the alternate player.

#### Versions

* foobar2000 version: v2.0 64-bit
* OpenLyrics version: 1.6

**Comment by sveakul** [comment]
I can add this additional information:

1.  The search failure from Musixmatch happens _only with an automatic, not a manual search,_ and only with tracks that contain _no album title metadata_ (i.e., 99% of all radio streams).
2. The failure on automatic in the above environment seems to affect only Musixmatch; tracks with no album name return auto results fine from Genius, AZLyrics, etc.

**Comment by jacquesh** [comment]
Can you please:
1. Enable debug logging for openlyrics (Preferences -> OpenLyrics-> Display -> 'Debug logging enabled')
2. Open the console (View -> Console), clear it (button in the bottom-left)
3. Reproduce the issue
4. Post the contents of the console window here

**Comment by sveakul** [comment]
Here are the console contents for the automatic search.  The file used has only the Artist, Track Title, and Date field embedded.  The only search source selected was Musixmatch.  I have also attached an image file showing the results for the same file using a Manual search, clearly showing that Musixmatch does indeed have the lyrics.

`Opening track for playback: "E:\New Mx\harry-nilsson-coconut.mp3"
Resampler (SRC): 44100 Hz sample rate is excluded
INFO-OpenLyrics: Failed to read search-avoidance info: Unsupported format or corrupted file
INFO-OpenLyrics: Searching for lyrics for artist='Harry Nilsson', album='', title='Coconut'...
INFO-OpenLyrics: Searching for lyrics in tag: 'LYRICS'
INFO-OpenLyrics: Searching for lyrics in tag: 'SYNCEDLYRICS'
INFO-OpenLyrics: Searching for lyrics in tag: 'UNSYNCED LYRICS'
INFO-OpenLyrics: Searching for lyrics in tag: 'UNSYNCEDLYRICS'
INFO-OpenLyrics: Failed to retrieve lyrics from source: Metadata tags
INFO-OpenLyrics: Querying for track ID from https://apic-desktop.musixmatch.com/ws/1.1/track.search?user_language=en&app_id=web-desktop-app-v1.0&subtitle_format=lrc&q_artist=Harry%20Nilsson&q_album=&q_track=Coconut&usertoken=
INFO-OpenLyrics: Rejected Musixmatch search result Harry Nilsson//Coconut due to tag mismatch: Harry Nilsson/Nilsson Schmilsson/Coconut
INFO-OpenLyrics: Rejected Musixmatch search result Harry Nilsson//Coconut due to tag mismatch: Harry Nilsson/Nilsson Schmilsson/Coconut (Remastered 2004)
INFO-OpenLyrics: Rejected Musixmatch search result Harry Nilsson//Coconut due to tag mismatch: Harry Nilsson/Nilsson Schmilsson/Coconut - Demo
INFO-OpenLyrics: Rejected Musixmatch search result Harry Nilsson//Coconut due to tag mismatch: Harry Nilsson/Let Me Get This Straight (Live)/Coconut - Live 1971
INFO-OpenLyrics: Rejected Musixmatch search result Harry Nilsson//Coconut due to tag mismatch: Harry Nilsson/Nilsson Schmilsson/Coconut (Remastered)
INFO-OpenLyrics: Failed to retrieve lyrics from source: Musixmatch
INFO-OpenLyrics: Save file name format '[%artist% - ][%title%]' with directory class 'ConfigDirectory' evaluated to 'file://C:\foobar2000-x64_v2\profile\lyrics\Harry Nilsson - Coconut'
INFO-OpenLyrics: Querying for lyrics in file://C:\foobar2000-x64_v2\profile\lyrics\Harry Nilsson - Coconut.lrc...
INFO-OpenLyrics: Querying for lyrics in file://C:\foobar2000-x64_v2\profile\lyrics\Harry Nilsson - Coconut.txt...
INFO-OpenLyrics: Found 0 lyrics in local files: file://C:\foobar2000-x64_v2\profile\lyrics\Harry Nilsson - Coconut
INFO-OpenLyrics: Failed to retrieve lyrics from source: Local files
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: Failed to read search-avoidance info: Unsupported format or corrupted file
INFO-OpenLyrics: Lyric loading complete
INFO-OpenLyrics: Received empty lyric update, ignoring...
![manual](https://github.com/jacquesh/foo_openlyrics/assets/130251824/43495997-2a14-46ca-9e53-3991048a70e9)
`

**Comment by sveakul** [comment]
Wanted to add that as Musixmatch never produces results from a radio stream due to this glitch, and the other sources do, the one thing streams have in common is that there is never an "Album Title" field sent, only track title and artist.  It could be that in the case of this one site it is reacting to an absent field it should not be considering.

**Comment by jacquesh** [comment]
Ah, looks like it's rejecting results that "don't match" because the tags don't contain an album name. I thought I'd specifically handled that but maybe not (or maybe only from the retrieved lyrics side).

I'll look into it, thanks

**Comment by jacquesh** [comment]
Auto- and manual-search do the same search underneath. The difference is that manual search gives you back *all* the results (so you can choose what to do with them) while auto-search needs to (by definition) automatically pick just one, and in an effort to do so sensibly, will filter out results whose metadata (artist/album/title) is sufficiently different from what fb2k has locally.

**Comment by sveakul** [comment]
> Ah, looks like it's rejecting results that "don't match" because the tags don't contain an album name. I thought I'd specifically handled that but maybe not (or maybe only from the retrieved lyrics side).
> 
> I'll look into it, thanks

Thanks jacquesh for looking into this, much appreciated.  As I mentioned, the way Genius and AZLyrics are handling the no-album for radio streams works fine.
