### ISSUE TITLE
Lyrics Saving to new Sub Folders

### ISSUE THREAD

**Issue by ngs428** [jacquesh/foo_openlyrics#267]
Also, I have noticed that if the artist/album/song have a "/" in the tag name openlyrics will save the lyric to a subfolder per where the "/" is in the name.  

This file tag: Elton John - Goodbye Yellow Brick Road (40th Anniversary) (2014 Remaster) - 01 - Funeral for a Friend /  Love Lies Bleeding

will save a lyric to a new folder:
"Elton John - Goodbye Yellow Brick Road (40th Anniversary) (2014 Remaster) - 01 - Funeral for a Friend "
with lyric named " Love Lies Bleeding.lrc"

**Comment by jacquesh** [comment]
This is working as intended, see the discussion on #244
