### ISSUE TITLE
[Nice-To-Have] Change the title of the taskbar icon to the current line on hover

### ISSUE THREAD

**Issue by DiscordTraveller** [jacquesh/foo_openlyrics#269]
This is a very very unneeded feature, just a nice-to-have.

Change the title of the taskbar icon to the current line on hover, by "title of the taskbar icon", I mean this
![image](https://github.com/jacquesh/foo_openlyrics/assets/94841148/89ac4619-b5d1-4674-a004-8e3ddc0426ed)
What it shows right now is the title of the song:
![image](https://github.com/jacquesh/foo_openlyrics/assets/94841148/72e6a2b8-31d6-431b-be82-ef528ab618ec)
I'm not even sure if foobar allows you access to the taskbar icon properties, just throwing this idea out there.

The reason this would be nice is because oftentimes I don't need to see all the lyrics, I just need to check on a line or two so it would be nice to just see it on hover.

**Comment by jacquesh** [comment]
I don't think this is possible with the current fb2k API, but tbh even if it were possible I don't know if I'd feel comfortable hijacking that tooltip (which is for all of fb2k) just to show a lyric (which would probably also have weird behaviour around changes, I suspect it won't update while you're hovering so if you wanted anything more than *one* line then that'd be annoying).

I'm going to try adding #41 for the next release which you might be able to use to solve your problem (if you made it a very small window that just shows the current line or something).
