### ISSUE TITLE
Add option to manually set lyric search keyword

### ISSUE THREAD

**Issue by geraltvoneich** [jacquesh/foo_openlyrics#27]
First let me thank you for the great plugin.

I have a bunch of files with foreign language meta data, which yield no results with the available lyric sources.
For the specific file even a search for the english title is unsuccessful (actually there would be an potential relevant result but for another artist name), but in general it would be handy to manually set search parameters.

Another more complex feature would be support for multiple languages in the meta data, e.g. 'Track Title [[Language]]', which would allow for things like dual/multi lyric rendering.

**Comment by jacquesh** [comment]
Can you provide an example of some files you have that yield no results (but do with other plugins or if you search the internet manually)?

Allowing you to manually set search terms would happen as part of #29.

It is unlikely that I will support multiple languages in the near future.

**Comment by jacquesh** [comment]
Closing this because it should be covered by the "manual search" feature of the 0.8 release.
