### ISSUE TITLE
"Mark as Instrumental" on a song with lyrics is crashing foobar2k

### ISSUE THREAD

**Issue by AdnoC** [jacquesh/foo_openlyrics#275]
I was managing my library, adding lyrics to songs that do not have them, when I decided that a song with 4 lines of lyrics should just have no lyrics at all (with my setup it will make things look better). I wanted to prevent OpenLyrics from re-downloading the lyrics, so I clicked the "Mark as Instrumental" button.

After some testing, it appears that if a song has lyrics, marking it as instrumental crashes foobar2k. I believe the lyrics need to be saved as tags for this to occur, but it may also happen if saved to file (I did not test that case).

#### Steps to reproduce
1. Install new foobar2k portable instance (2.0 32 bit)
2. Install foo_openlyrics-v1.6.fb2k-component
3. Add a song with lyrics (`LYRICS` tag) to foobar2k
4. Right click > OpenLyrics > Mark as Instrumental
5. It crashes

#### Expected behavior

Should just mark a song as instrumental.

#### Versions

* foobar2000 version: foobar2000 v2.0[x86]
* OpenLyrics version: 1.6

#### Additional information

Crash log: [failure_00000001.txt](https://github.com/jacquesh/foo_openlyrics/files/11842945/failure_00000001.txt)

**Comment by jacquesh** [comment]
Turns out I already fixed this for v1.7, I just noticed it locally and didn't put up a github issue for it.
