### ISSUE TITLE
Component is 'too eager' to update lyrics

### ISSUE THREAD

**Issue by stuerp** [jacquesh/foo_openlyrics#279]
When you edit the lyrics using the properties dialog (not via the Open Lyrics panel) of tracks that are NOT playing while another track IS playing all the edits are not saved (or overwritten by foo_openlyrics, difficult to tell).

#### Steps to reproduce
1. Play track A
2. Select track B and open its properties
3. Modify the lyrics of track B while track A is playing
4. Save the properties of track B and close the dialog
5. Open the properties of track B again

#### Expected behavior
The component should only process the playing track.

#### Versions
* foobar2000 version 2.0
* OpenLyrics version: 1.6

**Comment by Rexadev** [comment]
2 birds with 1 stone - https://github.com/jacquesh/foo_openlyrics/issues/219

**Comment by Rexadev** [comment]
@stuerp completed ?
