### ISSUE TITLE
[Feature-Request] Multi-Lyrics Panel 

### ISSUE THREAD

**Issue by lsusr** [jacquesh/foo_openlyrics#280]
Add the ability to search, save, and show different version (in language) of lyrics at the same time or just one. Example of this is Japanese song that have 3 different version of lyric Japanese, romanized, & English that maybe we can know what & how jp words in pronounced in the song, and the translation.

Yeah afterall, I don't know what I am talking about? Forgive me, and thanks for the components!

**Comment by Rexadev** [comment]
https://github.com/marz1877/SyncedLyrics-.lrc_v2

**Comment by jacquesh** [comment]
As mentioned in #170, specific handling for translations is beyond the current scope of openlyrics due to the significant complication it would introduce.
