### ISSUE TITLE
If you have 2 lyric files saved (or a lyric file and a text file, or two text files, whatever), which one will your plugin prioritize? The alphabetical one?

### ISSUE THREAD

**Issue by DitherMan420** [jacquesh/foo_openlyrics#285]
Just curious!

**Comment by jacquesh** [comment]
It will prefer .lrc files over .txt files. You can't have two .lrc or two .txt files with the exact same name, so it will use the one that exactly matches the tags on your track. There isn't really support for having multiple lyric files for the same track, there's just the one that it loads and possibly others (which are ignored and may as well not exist).

**Comment by DitherMan420** [comment]
That makes sense. Thank you!
