### ISSUE TITLE
Issue with saved file and location

### ISSUE THREAD

**Issue by Gabi-Schwartz-NI** [jacquesh/foo_openlyrics#290]
I've set the file format to: [%disc%-][%track% ][%title%] and the storage directory to "Same directory as track".
This works great but I found one song that's causing a problem.
It's by Bobbie Gentry from the album Ode to Billie Joe.
The song name is: **The Seventh Son (Demo) / Bonus Track**
This causes openlyrics to create a subfolder **1TNDI~N** and a file **Bonus Track.lrc**
If I rename the title to The Seventh Son (Demo) then it's ok and the file is save as: **1-11 The Seventh Son (Demo).lrc**
This new folder is probably due to the / in the tile.
I noticed that other invalid characters are being replaced but this one isn't.

#### Expected behavior
Save the file as: **1-11 The Seventh Son (Demo) _ Bonus Track.lrc** or anything else but do not create a subfolder

#### Versions
foobar2000: v2.0 32-bit
openlyrics: v1.6

**Comment by jacquesh** [comment]
This is working as intended, see discussion in #244
