### ISSUE TITLE
New release coming soon?

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#295]
Was just hoping you could give some idea of when the next release will be available.  The long-inoperative Musixmatch choice is sorely missed.  Thank you!

**Comment by jacquesh** [comment]
In a month? Maybe two? I don't know. I don't work to a schedule, I just make little bits of progress whenever I feel motivated to work on openlyrics. As you can see from [the next milestone page though](https://github.com/jacquesh/foo_openlyrics/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.7), there isn't a whole lot left that's scheduled to be included in the next release. One of those bugs is already fixed too, I just haven't pushed the code so github hasn't updated the tickets.

In general, if you're looking for a particular fix then it would be helpful if you could link that fix. In this case I assume you're referring to #265 (which is indeed fixed and will be part of the next release). As mentioned in that issue, you can work around the issue by making sure you have the correct Album tags.
