### ISSUE TITLE
Fullscreen/pop-out window

### ISSUE THREAD

**Issue by iammarxg** [jacquesh/foo_openlyrics#304]
Not necessary at all, but it would be nice to expand the lyrics into fullscreen. Would be great for karaoke, and if someone wants to see the lyrics only. Just like how you can toggle the foobar peak meter in fullscreen mode (see attached gif below).

![explorer_dTlNtBFih7](https://github.com/jacquesh/foo_openlyrics/assets/46378363/59d91edc-9d54-4403-85da-00f1a06f19c5)

Pop-out lyrics in a window would be nice too, but I don't see its significance at all compared to fullscreen.

Also, thank you for this great plugin :)

**Comment by jacquesh** [comment]
This is effectively covered by #41, for which experimental support is being added in the upcoming release :)
