### ISSUE TITLE
Default SKIP filter is wrong

### ISSUE THREAD

**Issue by regorxxx** [jacquesh/foo_openlyrics#306]
#### Steps to reproduce
1. New installation 1.7
2. Check Skip Filter
3. TF is has double parentheses by default
![image](https://github.com/jacquesh/foo_openlyrics/assets/83307074/835a402b-10ed-4a40-a97d-a78100ae0542)

#### Expected behavior
`$stricmp(%genre%,instrumental)$stricmp(%genre%,classical)`

#### Versions
* OpenLyrics version: 1.7

**Comment by jacquesh** [comment]
Meh. I saw this locally but I thought it was just the value I had saved, and didn't realise it was the default. I'll try get a bugfix release out soon (probably like next weekend or something) that address this and anything else major that comes up in the interim.

Thanks for reporting it!
