### ISSUE TITLE
Search for Lyrics not more working with DSF Files

### ISSUE THREAD

**Issue by Roendi61** [jacquesh/foo_openlyrics#311]
#### Steps to reproduce
1.  Search for Lyrics
2.  Status found
3.  Show Lyrics: No lyrics saved

#### Expected behavior
It works maby 1 Year ago. Longtime I run only the wizzard with out controlling the Files. 
So I have no Idea when the Problem starte

#### Versions
  
 1.7
* foobar2000 version:  2.0  x86
* OpenLyrics version: 1.7   I check some older versions. allways the same

#### Additional information

[console-2023-10-26-10-48-05-P12976.txt](https://github.com/jacquesh/foo_openlyrics/files/13175181/console-2023-10-26-10-48-05-P12976.txt)

**Comment by jacquesh** [comment]
The log you uploaded shows it saving to metadata tags. Specifically the `UNSYNCED LYRICS` tag.

Can you be a bit more specific about what you mean by "Show Lyrics: No lyrics saved"? Do you mean it searches the internet every time?

The log you provided does not show any search for Metadata tags. Can you try adding the "Metadata tags" source to the top of your search list and see if that fixes it?

**Comment by Roendi61** [comment]
Hi Jaquesh
You have the position search for Lyrics. This show all like it works. But when you go to the position: Show Lyrics: it say: No Lyrics saved. And its troue. 
Her another example with a older File. Is on unsynced Lyrics. I can see that with my DBpoweramp Edit ID Tag Tool
![Lyrics working](https://github.com/jacquesh/foo_openlyrics/assets/79584432/97ae0a87-3be5-457b-affd-cdf129dc8365)

I have no Settings like bevor.
![Settings](https://github.com/jacquesh/foo_openlyrics/assets/79584432/8a21f7f6-6728-45ea-a866-544ef1822bd0)

The log you provided does not show any search for Metadata tags. Can you try adding the "Metadata tags" source to the top of your search list and see if that fixes it?
![search](https://github.com/jacquesh/foo_openlyrics/assets/79584432/def667a4-c0df-4b7c-a38e-dbbdd993e139)

Nothing change

**Comment by jacquesh** [comment]
I'm struggling to understand the problem you're experiencing. You say that "Show lyrics" doesn't work, but then you provide a screenshot where it clearly *is* working. You say that "Search for lyrics" is working, but the logs you provided show it searching QQMusic and Netease (the default providers) and not any others (in particular not Metadata tags).

You mention that you can see the tags (that openlyrics doesn't find) using dbpoweramp. Is that true when those lyrics tags were saved by openlyrics itself (such as the one shown in the log you provided)? Or are these only files that were saved previously? Does openlyrics load the tags saved in the log you uploaded?

**Comment by Roendi61** [comment]
I feel the same way. But no matter. I will now describe and document the exact error process.

Step 1: Search for lyrics with Open lyrics
![Suche](https://github.com/jacquesh/foo_openlyrics/assets/79584432/cdfe9802-aa66-4a2c-a431-1f2b2a4c811a)

Step 2: Lyrics found
![Found](https://github.com/jacquesh/foo_openlyrics/assets/79584432/58cf4f13-e140-4e95-bfd2-c802b476939e)

Step 3: Display lyrics
![Show lyrics](https://github.com/jacquesh/foo_openlyrics/assets/79584432/e75468a3-3e4b-4710-a455-ff0dc2ca619c)

Step 4: No lyrics saved
![No Lyrics](https://github.com/jacquesh/foo_openlyrics/assets/79584432/2f254ab4-083f-479c-a06c-b81eaade697f)

I hope the Prozess is now clear for you

**Comment by Roendi61** [comment]
I do the same with a Flac File. And with Flac the program works fine. Its only a Problem with DSF Files.

**Comment by jacquesh** [comment]
Ooooh, sorry now I understand. The problem is the *.dsf files. Right. I believe decoding for those is provided by a 3rd-party component, it's not supported natively in fb2k, correct? Do we have any evidence that said plugin supports saving to metadata tags using the usual fb2k tag-editing code? I expect it does not because openlyrics doesn't pay any attention to the format, it just uses the built-in APIs for modifying tags.

I recommend either saving to file or converting those files to another format.

**Comment by Roendi61** [comment]
OK No problem
I recommend either saving to file or converting those files to another format.
Both are not a valid option at the Moment.
Thanks for your support
