### ISSUE TITLE
1.7 and 1.8: lyrics no longer display and cannot be edited

### ISSUE THREAD

**Issue by H2Swine** [jacquesh/foo_openlyrics#315]
Upgraded. OpenLyrics panel now shows "Artist:", "Album:" and "Title:" - but no lyrics. Yes the file in question has lyrics in tags. 
Double-click? Blank pane. Try the one with debug symbols (whatever that is ...), and it doesn't even react to the pane, it asks me whether I want a playlist there. 

Reinstall 1.5 or 1.6, and all works again. 

fb2k version 2.1 preview 2023-10-13 [x86] (i.e. 32-bit).

**Comment by jacquesh** [comment]
Hmm, well that's obviously bad. I don't recall making any changes to tag-loading code (certainly not any particularly significant changes), and certainly a basic test of loading from tags on my machine (running fb2k v2.0 x86) works as expected.

Could you upload a debug log of the issue?

**Comment by H2Swine** [comment]
There is definitely something weird going on here. Pasting from console window: 

```
INFO-OpenLyrics: LyricPanel::compute_background_image took 589us
INFO-OpenLyrics: LyricPanel::compute_background_image took 2198us
Resampler (RetroArch): 44100 Hz sample rate is excluded
INFO-OpenLyrics: Playback is currently active, using the now-playing track for format preview
INFO-OpenLyrics: Spawning editor window...
INFO-OpenLyrics: Expanding lyric text...
INFO-OpenLyrics: Initializing editor window...
```

Obviously the Resampler message is unrelated. 
Then afterwards I double-clicked and got the "Spawning editor window"  etc. 
Looks normal?!

Well now I found out about that external window function. Right-click and open that. Now for sudden the lyrics also show in the normal window. Console output: 

```
INFO-OpenLyrics: LyricPanel::compute_background_image took 968us
INFO-OpenLyrics: LyricPanel::compute_background_image took 2005us
INFO-OpenLyrics: Successfully created D3D device using driver type 0x1
INFO-OpenLyrics: ExternalLyricWindow::SetUpDX took 35553us
INFO-OpenLyrics: LyricPanel::compute_background_image took 1014us
INFO-OpenLyrics: DirectX target size has not changed and setup was not forced, skipping setup...
INFO-OpenLyrics: ExternalLyricWindow::SetUpDX took 75us
INFO-OpenLyrics: Successfully created D3D device using driver type 0x1
INFO-OpenLyrics: ExternalLyricWindow::SetUpDX took 18797us
INFO-OpenLyrics: LyricPanel::compute_background_image took 1688us
INFO-OpenLyrics: No search avoidance info available for track
INFO-OpenLyrics: Searching for lyrics for artist='2 Ton Predator', album='Demon Dealer', title='Bone Brigade'...
INFO-OpenLyrics: Searching for lyrics in tag: 'SYNCEDLYRICS'
INFO-OpenLyrics: Searching for lyrics in tag: 'SYNCED LYRICS'
INFO-OpenLyrics: Searching for lyrics in tag: 'LYRICS'
INFO-OpenLyrics: Found lyrics in tag: 'LYRICS'
INFO-OpenLyrics: Searching for lyrics in tag: 'UNSYNCED LYRICS'
INFO-OpenLyrics: Searching for lyrics in tag: 'UNSYNCEDLYRICS'
INFO-OpenLyrics: Successfully retrieved lyrics from source: Metadata tags
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Loaded lyrics already form a valid UTF-8 sequence
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: Lyric loading complete
INFO-OpenLyrics: Skipping lyric save. Type: 1, Local: yes, Timestamped: yes, Autosave: 2
```

Closing the external window, and it still shows in the OpenLyrics window - and scrolls, because I had synced lyrics.

Now, what next ... open another track with synced lyrics, open the external window, right ... 
... change track ...
... fb2k crashes!

**Comment by H2Swine** [comment]
But, even weirder: 
- I got it to work in a portable version with the same components as the ones I usually use.
- But not when I copied over the theme.fth file. So it doesn't like that one.

**Comment by jacquesh** [comment]
Hmmm, yeah sounds like an issue with handling multiple panels. I had a lot of trouble with that while working on 1.7, but I thought I'd managed to get it fixed properly. That's disappointing.

That seems like it might also explain not seeing lyrics because part of that change was to have just one panel do the searching (rather than having each panel do its own search, which might cause them to interfere with each other and is just more searching than necessary). Sounds like I've missed something in that logic.

I'll look into it but until it gets fixed I guess the workaround is to keep to a single panel. Thanks for the info!

**Comment by svshepherd** [comment]
I am also having this problem, and I also have a layout that includes multiple lyrics panels (arranged differently depending on my needs at the time).

**Comment by svshepherd** [comment]
Follow up: once I chased down *which* of the lyrics windows was active, *all* of the windows started behaving. @H2Swine when you found the active panel, did the others start working for you?

**Comment by H2Swine** [comment]
@svshepherd Didn't outright test - when I deleted the tab containing the second element, and the lyrics started to show, I did not re-add it. 
But I experenced something "similar" yes. Quoting myself above: 
> found out about that external window function. Right-click and open that. Now for sudden the lyrics also show in the normal window. Console output:

**Comment by svshepherd** [comment]
@H2Swine thanks! Nice to triangulate.

**Comment by cheatfreak47** [comment]
Confirming this issue, if you have more than one Lyrics panel anywhere in the GUI (even in tabs you aren't actively looking at) all but the first one won't display lyrics correctly unless you go look at that first one. This is a pretty annoying usability issue if you like having multiple layouts.

**Comment by hkmelee** [comment]
reload music info can be fix problem.
foobar2000 v2.1.2[x64]
OpenLyrics v1.8

**Comment by cheatfreak47** [comment]
can confirm this is fixed, thanks and nice job!
