### ISSUE TITLE
Opening same song twice causes album art to disappear

### ISSUE THREAD

**Issue by prank855** [jacquesh/foo_openlyrics#318]
#### Steps to reproduce
1. Open track to play
2. Open it again

#### Expected behavior

Album art should stay

#### Versions
* foobar2000 version: v2.0 x86
* OpenLyrics version: 1.8

#### Debug logs
```
Opening track for playback: "D:\_fb2k\S3RL - Bass Slut.mp3"
Autosave (T) skipped, last saved less than 30 seconds ago.
Opening track for playback: "D:\_fb2k\S3RL - Bass Slut.mp3"
Autosave (T) skipped, last saved less than 30 seconds ago.
```

**Comment by regorxxx** [comment]
Reproduced.

**Comment by Rexadev** [comment]
https://github.com/jacquesh/foo_openlyrics/assets/62152714/46408fbc-c6f5-45d3-90cd-b5ed7a2534f8
