### ISSUE TITLE
Musixmatch search gives 401 despite working live token

### ISSUE THREAD

**Issue by aaronliu0130** [jacquesh/foo_openlyrics#319]
#### Steps to reproduce
1. Get a free/testing tier API key
2. input it to openlyrics
3. doesn't work

#### Expected behavior
It should show the first 30% of the lyrics

#### Versions
* foobar2000 version: 2.0
* OpenLyrics version: 1.8

#### Debug logs
`WARN-OpenLyrics: Received musixmatch search result but body was malformed: {"message":{"header":{"status_code":401,"execute_time":0.002,"hint":"renew"}}}`
![image](https://github.com/jacquesh/foo_openlyrics/assets/11874211/dff49a8d-7fe1-4743-ad5e-af3c003bcbc2)
![image](https://github.com/jacquesh/foo_openlyrics/assets/11874211/eea79e87-98ef-4747-aae1-f8eb69c0710c)
![image](https://github.com/jacquesh/foo_openlyrics/assets/11874211/46ec3635-5c93-4762-923b-98657aac8a11)

**Comment by yalov** [comment]
I have the same problem.
Has anyone been able to make Musixmatch work with OpenLyrics?

**Comment by aaronliu0130** [comment]
I guess you need to pay for musixmatch.

**Comment by jacquesh** [comment]
As you say, there are limits on usage of the freely-available API keys. I can confirm it generally works for me so it's at least not *always* broken.
