### ISSUE TITLE
Track title with slash "/"

### ISSUE THREAD

**Issue by Sevenuno** [jacquesh/foo_openlyrics#320]
I have all lyrics saved in "foobar2000\lyrics" folder.
When track title comes with a slash "/" such as "Just Like Fire / Heartbreaker (Live)", it will save the downloaded lyric as "foobar2000\lyrics\P!nk - Just Like Fire\ Heartbreaker (Live).lrc.
i.e. it will create a sub-folder named "P!nk - Just Like Fire"

#### Steps to reproduce
1.
2.
3.

#### Expected behavior
lrc file should be saved as "P!nk - Just Like Fire _ Heartbreaker (Live).lrc" within the folder "foobar2000\lyrics".

#### Versions
* foobar2000 version: 2.0
* OpenLyrics version: 1.8

**Comment by jacquesh** [comment]
Working as intended, I should expand the default replacement filter to catch backslashes as well.

See #244 for the previous discussion. I suggest you wrap the configured "File name format" for the local files source in an appropriate "$replace()" call.
