### ISSUE TITLE
Metal Archives handling of lyrics

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#323]
This is just to chime in on your message to H2Swine about having Openlyrics continue to search past Metal Archives if the results produce a "(lyrics not available)" return.

The Metal Archives website returns the message "(lyrics not available)" if an Advanced Search (Band and song title) DOES find a hit for that band and song on the website but the lyrics for that song are not available to them.  In that case, clicking on the "Lyrics" column in the Search results will show the "(lyrics not available)" message below the search results line.  A full example is below:

![lyrics](https://github.com/jacquesh/foo_openlyrics/assets/130251824/144d989b-92dc-4de5-a16d-c05b9d8f557a)

It would be nice if OpenLyrics could interpret that as a non-hit and just continue to another provider.  Another popular source that behaves like this is **SongLyrics**, which in the same circumstance will return a message "We do not have have the lyrics for (song title) yet" and the search stops. Example from website:

![songlyrics](https://github.com/jacquesh/foo_openlyrics/assets/130251824/9bc4d2ed-bfc4-4c04-98b4-22ce9a4349bd)

**Comment by jacquesh** [comment]
Thanks for the examples. Tagging @H2Swine for visibility in case they'd like to add anything or track this.

For completeness, the comment you're referring to is in #253 (specifically [this one](https://github.com/jacquesh/foo_openlyrics/issues/253#issuecomment-1872314524))

**Comment by H2Swine** [comment]
Just for simple examples in the Metal Archives lyrics URL format: 
Available: https://www.metal-archives.com/release/ajax-view-lyrics/id/1234
Not available: https://www.metal-archives.com/release/ajax-view-lyrics/id/12345

**Comment by Rexadev** [comment]
@jacquesh show a popup to notify user of new features and sources I just remembered metal-archived is added
