### ISSUE TITLE
Blank screen when wanting to configure the plugin. 

### ISSUE THREAD

**Issue by deroverda** [jacquesh/foo_openlyrics#326]
The lyrics are working as usual but i wanted to check my settings but all I see is a dark background with a little box that I can tick (debug logging enabled)

#### Steps to reproduce
1. dont
2. know

#### Expected behavior
showing me the settings as usual

#### Versions
* foobar2000 version: 2.1.1 [x86}-
* OpenLyrics version: latest

#### Additional information

![foobar2000_20240118_4s](https://github.com/jacquesh/foo_openlyrics/assets/70813982/eabf6aaa-21d5-490f-8c9b-61f1facb8f24)

**Comment by jacquesh** [comment]
This is by design. You need to expand the subtree on the left-hand side to see the other OpenLyrics options.
