### ISSUE TITLE
Dynamically change text size when changing panel size

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#334]
### Example can see space waste when changing panel size
https://github.com/jacquesh/foo_openlyrics/assets/62152714/52e1201a-1086-4495-9202-2cc08cc789da

### Example can see space waste when lines are not long
![image](https://github.com/jacquesh/foo_openlyrics/assets/62152714/9b2867b9-69be-4509-9dbc-9c9bcae867cf)

**Comment by Rexadev** [comment]
@jacquesh consider this feature for next update

**Comment by jacquesh** [comment]
I'm not convinced this is worth doing. The first issue is that "lines are not long" is wholly dependent on the lyrics being shown and in my experience varies significantly by track and by lyric (different lyrics from different sources tend towards longer or shorter lines).

Moreover, I generally assume that layouts change very infrequently and if you find that your panel is too large for your font size then you can always change the font size to fit better. I expect that dynamically determining font size would be annoying and the consistency would be preferable to having every track use a different font size. I'm pretty sure *I* would find it annoying at least.

To take a step back though: Does it matter if the lyrics don't fill the available horizontal space? If they're large enough to read consistently then is that not fine already? It just feels to me like it would provide minimal benefit for the extra complexity.

**Comment by jacquesh** [comment]
Out of scope.
