### ISSUE TITLE
[Source] thebeatles.com/my-life

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#338]
https://www.thebeatles.com/my-life
https://www.thebeatles.com/songs

I didn't find a song that is not available in current sources but,
Official sources should be preferred because it is correct
Why make source for 1 band ? thier lyrics are good.
Most popular old rock band.

**Comment by jacquesh** [comment]
I don't think it's not worth the initial (and ongoing) development effort to build an extra source just for a single artist, especially not when lyrics for those artists are already widely available on other sources. True, they might be considered the canonical source, but many lyrics websites (such as Genius) allow/encourage community contributions.
