### ISSUE TITLE
Songs with featuring artist is named different. Problem is &/and ,/and

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#340]
#### Steps to reproduce

![image](https://github.com/jacquesh/foo_openlyrics/assets/62152714/6243dd5c-dcff-47b4-bcba-acdfc4d3ad96)

#### Expected behavior

https://genius.com/Dimitri-vegas-and-like-mike-and-david-guetta-complicated-lyrics

#### Versions

* foobar2000 version: 2.0
* OpenLyrics version: 1.8

#### Debug logs

```
ERROR-OpenLyrics: Error of unrecognised type while searching AZLyrics.com
Library scanning problem: "...\1 foobar2000 v2 Portable\profile\eslyric-data\scripts\lib\crypto-es\lib\index.d.ts", reason: Unsupported format or corrupted file
Opening track for playback: "...\Dimitri Vegas & Like Mike, David Guetta, Dimitri Vegas, Kiiara\Complicated.opus"
WARN-OpenLyrics: Failed to download darklyrics.com page http://darklyrics.com/lyrics/dimitrivegaslikemike/complicated.html: Object not found
WARN-OpenLyrics: Failed to download genius.com page https://genius.com/dimitri-vegas-and-like-mike-complicated-lyrics: Forbidden (403)
ERROR-OpenLyrics: Error of unrecognised type while searching AZLyrics.com
```

**Comment by jacquesh** [comment]
As per the bug issue template: Please include debug logs of a minimal reproduction of the issue.

**Comment by Rexadev** [comment]
@jacquesh added

**Comment by jacquesh** [comment]
Your artist tag doesn't include `and David Guetta` at the end, and that's what Genius expects. We're not using a search API for Genius, we're just looking up the exact page for the track being searched. If the URL we compute for that doesn't exactly match what Genius used then it won't find it.

**Comment by Rexadev** [comment]
>we're just looking up the exact page for the track being searched. If the URL we compute for that doesn't exactly match what Genius used then it won't find it.

That the problem. `&`/`and` `,`/`and`/`vs`

Same song with artists listed differently 
https://en.wikipedia.org/wiki/Complicated_(Dimitri_Vegas_%26_Like_Mike_and_David_Guetta_song) Complicated (Dimitri Vegas & Like Mike and David Guetta song)
https://www.youtube.com/watch?v=w0EF3AxJwLU - Dimitri Vegas & Like Mike vs David Guetta ft. Kiiara - Complicated (Official Music Video)
https://genius.com/Dimitri-vegas-and-like-mike-and-david-guetta-complicated-lyrics Complicated
[Dimitri Vegas & Like Mike & David Guetta](https://genius.com/artists/Dimitri-vegas-and-like-mike-and-david-guetta)
