### ISSUE TITLE
WebP AlbumArt doesn't show as background.

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#341]
#### Versions

* foobar2000 version: 1.8
* OpenLyrics version: 2.0

#### Debug logs

```
Opening track for playback: "...\Busta Rhymes\Busta Rhymes - Calm Down (Audio) ft. Eminem.mp3"
Opening track for playback: "...\NF\CLOUDS.mp3"
Opening track for playback: "...\Busta Rhymes\Busta Rhymes - Calm Down (Audio) ft. Eminem.mp3"
WARN-OpenLyrics: Failed to load album art image
```

#### Additional information

![image](https://github.com/jacquesh/foo_openlyrics/assets/62152714/4c5abc8f-6a9c-41c1-ad71-e4d45e50fd25)
![image](https://github.com/jacquesh/foo_openlyrics/assets/62152714/dbff9d71-f554-4f3e-bd03-3efcea85bf60)
![image](https://github.com/jacquesh/foo_openlyrics/assets/62152714/75db9cbb-ed59-4915-a5ae-2f6389c88e4d)
![image](https://github.com/jacquesh/foo_openlyrics/assets/62152714/afda871c-cf16-4e00-a37c-4ec10373c3d9)

**Comment by jacquesh** [comment]
There is almost no info in this issue (no debug logs of it failing, no example images, nothing to demonstrate that fb2k itself supports webp album art, etc).

If you're not even going to put in a minimal amount of effort to demonstrate the issue you want fixed, then I'm not going to feel particularly strongly compelled to put in the effort to implement the change you're requesting.

**Comment by Rexadev** [comment]
@jacquesh please check the main thread i have added all info you asked for

**Comment by marc2k3** [comment]
WebP support in 3rd party components has nothing to do with fb2k itself. The changelog explicitly says "Default UI, properties dialog".

It's always been possible for developers to display WebP but it's up to them to decode the album_art_data_ptr they retrieve from various SDK methods.

As an example, I do it with libwebp here...

https://github.com/jscript-panel/Helpers/blob/6e9467f7bd0d6a97f36916ddc66d6c34d53c3fa1/ImageHelpers.cpp#L59-L77

It's also possible using the windows imaging component.

https://learn.microsoft.com/en-us/windows/win32/wic/-wic-about-windows-imaging-codec

WebP is supported natively on windows 10 and later.

An example of that is here...

https://github.com/jscript-panel/Helpers/blob/6e9467f7bd0d6a97f36916ddc66d6c34d53c3fa1/ImageHelpers.cpp#L46-L57

In that 2nd example, I have to go from album_art_ptr -> IStream first.

**Comment by Rexadev** [comment]
@jacquesh please fix this one

**Comment by jacquesh** [comment]
In the next release we use the windows imaging decoder, which supports WebP but you will need to have the [WebP Image Extensions](https://www.microsoft.com/store/productId/9PG2DK419DRG?ocid=pdpshare) installed from the Microsoft store.

Thanks for the pointers @marc2k3 :)

**Comment by marc2k3** [comment]
For those not on windows 10/11 or don't use the store, this can be installed to enabled WebP via WIC as well...

https://storage.googleapis.com/downloads.webmproject.org/releases/webp/WebpCodecSetup.exe
