### ISSUE TITLE
[Feature] Add button to switch between SYNCEDLYRICS and LYRICS

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#344]
Alternative solution to problem https://github.com/jacquesh/foo_openlyrics/issues/166

**Comment by jacquesh** [comment]
"Alternative solution" is not a description. If you want a feature please provide a detailed description of your desired behaviour.

**Comment by Rexadev** [comment]
1 file can have 2 metadatafields for synced and unsynced lyrics add a feature to switch between them
