### ISSUE TITLE
[Feature] When using AutoSearch Show the first lyrics found then after the search is complete switch to the ""best" one

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#345]

**Comment by jacquesh** [comment]
1. Once again, please provide a detailed description for all feature requests.
2. That's not how autosearch works, it stops after it finds a matching result, that's why you configure an order in which to search sources
3. How do you propose we would event determine what the "best" lyrics are?

**Comment by Rexadev** [comment]
@jacquesh reopen this please
