### ISSUE TITLE
[Feature] Userdata base to share best URL and offset for a song

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#346]
Recently dev added a telemetry to better understand the users. Maybe this feature doesn't take that much more effort.

1. Users can choose to upload to server which source they choose for a song when manually selecting lyric.
2. Also option to upload offset for a lyric URL.
----------
1. User can be shown percentage of users choosing a source
2. Asked to also download offset value for it.
3. Automatically download from top URL

### Metadata to get from user -
1. Artist
4. Title
5. Format (mp3 has silence at the start)
6. Length - Songs can be of different versions (radio,single,album,...) or different sources have 1-4 seconds of silence at ends.
7. Album

**Comment by jacquesh** [comment]
This would be well beyond the scope of a lyrics plugin and would be its own project.
Feel free to build this yourself and when it's ready, maybe openlyrics could integrate with it.
