### ISSUE TITLE
Any way to embed synced lyrics into the file metadata?

### ISSUE THREAD

**Issue by SonOfTheKingdom** [jacquesh/foo_openlyrics#347]

**Comment by Rexadev** [comment]
That's what happens

**Comment by jacquesh** [comment]
Yes, set "Preferences -> OpenLyrics -> Saving -> Save method" to "Save to tag"

**Comment by SonOfTheKingdom** [comment]
The only option that appears is "Debug logging enabled". I'm new to foobar2000, am I looking in the wrong place?

**Comment by SonOfTheKingdom** [comment]
Got it, I didn't see I needed to expand the submenu. All I was getting was "Debug logging enabled. Thank you so much.
