### ISSUE TITLE
consider implementing parallel lyric fetching to increase speed

### ISSUE THREAD

**Issue by veksha** [jacquesh/foo_openlyrics#35]
i'm playing with parallel requests in my foo_multisource and soon will rewrite every lyric-source to make support for this. but as you know LSP3 is abandonware. even if results of one source will be in parallel mode LSP still doing sequential loop of every source.

I suggest to consider parallel model design that will enable openlyrics to be the fastest lyric retriever.

**Comment by jacquesh** [comment]
Good idea! It'll probably require some refactoring of the existing search mechanism, but we're already running the search itself asynchronously by necessity anyway so it shouldn't be too complicated to do.
