### ISSUE TITLE
Get Lyrics on Phone from PC via LAN

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#357]
Get Lyrics of currently playing song on foobar2000 Windows on Android via LAN

1. Option to see many lyrics
2. See on Multiple Phones

**Comment by jacquesh** [comment]
Is this even possible? As far as I know foobar2000 on Android does not support running custom components.

**Comment by jacquesh** [comment]
Closing at least until we know that fb2k mobile supports components and openlyrics is one of them.

**Comment by Rexadev** [comment]
Something like https://github.com/TheQwertiest/foo_discord_rich can get song title and https://github.com/shub39/Rush can get song lyrics from internet or LAN

**Comment by Rexadev** [comment]
Add option to view lyrics view network
Maybe you can use this project's code https://github.com/KonstantinosPetrakis/SyncLyrics
