### ISSUE TITLE
QQ lyrics contains special html entities like &apos;

### ISSUE THREAD

**Issue by veksha** [jacquesh/foo_openlyrics#36]
example: `3 - Alien Angel`
```
[01:50.18]You could&apos;ve been
```

**Comment by jacquesh** [comment]
I am aware of this, but in general I'm trying to avoid making automated & unconfigurable edits to lyrics (rather providing them as is and letting the editor give you the tools to fix them).

There is already an auto-edit to fix this particular issue ("Replace &-named HTML characters") and #25 exists to provide the option for some auto-edits to run...well...automatically...which I believe would entirely resolve this issue.

That said, I am open to being convinced that this is a QQ-specific encoding issue and that we should just always do this for QQ lyrics.

**Comment by veksha** [comment]
sorry, I should've used search before opening another issue. But I think most people will be happy with "autofix" from the get-go. to just sing along to a song without being stopped by some cryptic line. autofix can be nice as a "sane default". and for the hackers and purists there can be some option like "get raw results" :-)
my personal opinion.

**Comment by jacquesh** [comment]
No problem. Yeah you're probably right. I'll can make it set the auto-html-decode to "enabled" (run automatically) by default when #25 gets done.
