### ISSUE TITLE
Add ability to display source of found lyrics

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#362]
Please add the ability to see the source where foo_openlyrics found the displayed lyrics.

The use case for this is to make judgements as to what sources are providing the best results for the particular listener and then being able to prioritize those on the search order panel.

This could be added to a right-click panel option like "show source", or selectable as a preface line in the lyrics themselves.  Examples below from ESlyric and LSP3/multisource:

![eslyric](https://github.com/jacquesh/foo_openlyrics/assets/130251824/7bbbde05-a3b8-46d9-b7b3-8c62800882ac)

![multi](https://github.com/jacquesh/foo_openlyrics/assets/130251824/c99250a9-8f45-4999-bf89-4e6fea650a3b)

![lsp](https://github.com/jacquesh/foo_openlyrics/assets/130251824/e9aabc72-97c9-4477-83bf-9a7a8d640d53)

**Comment by Rexadev** [comment]
https://github.com/jacquesh/foo_openlyrics/issues/187

**Comment by jacquesh** [comment]
Very similar to #52

**Comment by jacquesh** [comment]
I think the main concern here is: Where do we store this information? In LRC we can store it in the tags, but that doesn't work for unsynced lyrics, so we basically need to store it in a metadb in fb2k. That has the downside that if you ever modify them outside  of fb2k, that info will just be wrong...although I guess we could also store a hash of the lyrics and compare against that to see if they've been modified ¯\_(ツ)_/¯

**Comment by Rexadev** [comment]
> we can store it in the tags

https://github.com/jacquesh/foo_openlyrics/issues/187

Store it in tags for unsynced too and let foo_openlyrics ignore it when playing and hope other lrc software catchup.

**Comment by jacquesh** [comment]
It would certainly be simpler to implement, but the problem with not persisting source information is that the source will then just be "local files" (or whatever your save source is) most of the time. That seems a bit unhelpful...

**Comment by Rexadev** [comment]
@jacquesh What is different in this issue compared #187 ?

**Comment by Rexadev** [comment]
@jacquesh Is always shows source as `Metadata Tags` eg.
```
Retrieved from Metadata tags @ SYNCEDLYRICS
First retrieved from Metadata tags at 2024-09-11 11:15:28 @ SYNCEDLYRICS
```
