### ISSUE TITLE
"Save to tag" still saves to text file when playing web radio streams

### ISSUE THREAD

**Issue by Ciancy28** [jacquesh/foo_openlyrics#365]
When playing web radio streams with metadata and openlyrics finds lyrics for the current playing song, lyrics get saved to text file even if save method is set to "Save to tag", causing the folder to needlessly fill up with hundreds of .lrc files for songs that I'll probably never listen to again.

#### Steps to reproduce
1. listen to a web radio that provides metadata
2. browse "C:\Users\<user>\AppData\Roaming\foobar2000-v2\lyrics
3. check for .lrc files related to songs that played during stream playback

#### Expected behavior
folder should be empty

#### Versions
* foobar2000 version: 2.1.5 [x64]
* OpenLyrics version: 1.8

#### Debug logs
[console-2024-06-05-04-55-19-P3684.txt](https://github.com/user-attachments/files/15572515/console-2024-06-05-04-55-19-P3684.txt)

#### Additional information
Now that I'm thinking about it, this might actually be intended behaviour, and some users might find it useful to keep tags as text files for audio streams, if this is the case, I suggest adding some other option, maybe renaming the current one to "Save to tags (when available)" or something along those lines, and treat this as a feature request rather than a bug report.

**Comment by jacquesh** [comment]
Indeed, this is intended behaviour (because we don't have a media file to save the tags to).

Yes technically we could add an option to not save to tag when you're listening to a radio stream but adding more options is itself not really desirable, it's a pretty niche case and....does it matter? So let's say you have 500 lyrics for tracks you'll never listen to again...is that a problem? How so?

**Comment by Ciancy28** [comment]
> Indeed, this is intended behaviour (because we don't have a media file to save the tags to).
> 
> Yes technically we could add an option to not save to tag when you're listening to a radio stream but adding more options is itself not really desirable, it's a pretty niche case and....does it matter? So let's say you have 500 lyrics for tracks you'll never listen to again...is that a problem? How so?

Sounds fair
no, it's not really a problem in the end, feel free to close the issue if you don't feel like implementing this makes sense.

**Comment by jacquesh** [comment]
Yeah, at least at this point I think its a bit too niche and not really enough of an issue that I'd rather not add another option for it (we already have lots of options and keeping that complexity under control is important).

Thanks for being understanding though, and for the detailed initial report/request <3
