### ISSUE TITLE
"Focus on more lyric sources" for 1.10

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#371]
In addition to LRCLIB which has its own thread here, two others mentioned here previously that would be priorites in the 1.10 emphasis on adding sites IMO are Bandcamp and SongLyrics, which in my heavy radio stream listening pick up a lot of what the heavy-hitters may leave.

**Comment by jacquesh** [comment]
I've adde bandcamp to the milestone, LRCLib was already in there.

SongKick has not been mentioned here previously. If you would like it to be added to the list of available sources, please put in a ticket for it as per the usual template.
