### ISSUE TITLE
Show Time Remaining/Total Time

### ISSUE THREAD

**Issue by ReallyTryingToLearnCPlusPlus** [jacquesh/foo_openlyrics#375]
I switched over to foo_openlyrics from foo_uie_lyrics3 due to the frequency of issues present in pulling lyrics there, however, one notable seeming omission in foo_openlyrics compared to its earlier predecessor seems to be a lack of playtime when lyrics aren't found--I tend to rely on that for easy visibility compared to the indicator in the bottom left of the window, simply because it's convenient to have all the info in one place (title, artist, album, time.) 
That said, it seems like it _should_ be there from poking around in the source, so I'm not sure whether this is a bug on my part (I am running v.1.6.2 of foobar2000, with 1.9 of foo_openlyrics) or not. Regardless, I do not see a playback timer, so I am suggesting it to be incorporated or as a toggle to bring it in line with the former lyrics component.

**Comment by jacquesh** [comment]
This would be solved by #57 

> That said, it seems like it should be there from poking around in the source

Not sure what you mean by this. Can you link to some specific code? I don't think openlyrics has ever shown playtime in the lyrics panel...
