### ISSUE TITLE
Always save lyrics to new setting

### ISSUE THREAD

**Issue by aaronliu0130** [jacquesh/foo_openlyrics#379]
Apologies for the bad title. What I mean surrounds the "Save lyrics to" setting. However, this setting only applies to lyrics saved after the settings change. What I'm thinking is that maybe there should be a toggle so that the extension automatically saves to the new target when it detects lyrics saved to the old target.

**Comment by jacquesh** [comment]
This sounds to me like a good candidate for a separate standalone tool that you can run as a once-off migration instead of being built into openlyrics. Openlyrics will happily load from both files and tags and most other lyric plugins will too.
