### ISSUE TITLE
Artists are combined when a song has multiple artists, resulting in bad results

### ISSUE THREAD

**Issue by Big-aap** [jacquesh/foo_openlyrics#38]
When a song has multiple artists (separated with a "; " in the tags so foobar2000 recognizes them as separate artists), the plugin **combines these artists without a space inbetween in the artist field.**
https://i.imgur.com/XtfDQHR.png

When just using the first artist, the results are good.
https://i.imgur.com/35NTCe9.png

I had a similar problem with a lastfm scrobbling plugin which could be fixed by **using "$meta(artist,0)" as the artist.**
(screenshot of the settings and link to the plugin in case it is helpful)
https://i.imgur.com/d6ycbGy.png
https://github.com/gix/foo_scrobble

**Comment by jacquesh** [comment]
Ah, yeah currently OpenLyrics concatenates all instances of the same tag. I did that initially because I wasn't sure in what situations there'd be multiple tags.

Now we have a single data point, its pretty simple to just ignore every tag after the first one.
