### ISSUE TITLE
External lyrics window doesn't respect custom font color when no lyrics are found

### ISSUE THREAD

**Issue by sig-kill** [jacquesh/foo_openlyrics#380]
#### Steps to reproduce
1. Set custom background to black
2. Set custom main text color to something that isn't black
3. Play a song that doesn't have lyrics, so the external viewer only shows the song info.
4. Text color seems hard-coded black: 
![image](https://github.com/user-attachments/assets/6280a4d2-064c-45b1-9fec-7d409007dc88)
, making it very difficult to see on dark background colors.

#### Expected behavior

The text should use either the "Custom main text color" or "Custom highlight color" by default:
![image](https://github.com/user-attachments/assets/96650318-1100-4b41-9a1e-991d3d9a6621).
Currently it only uses this color when the mouse is hovered.

#### Versions

* foobar2000 version: v2.2 preview 2024-08-14 x64
* OpenLyrics version: 1.9

#### Debug logs

N/A

**Comment by jacquesh** [comment]
Oh that's a silly bug on my part, thanks for reporting it! It's been fixed for the next release :)
