### ISSUE TITLE
Option to only get SyncedLyrics from Synced-Lyrics Sources atleast in AutoSearch/Bulk

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#381]
I like Genius UnSynced lyrics and MusixMatch is the only option for SyncedLyrics and MusixMatch also having unsyncedlyrics is causing problems in auto-search/bulk-search.

**Comment by Rexadev** [comment]
#215 is similar, there I mean to manually only search for synced lyrics aand here I mean only for autosearch/Bulk

**Comment by Rexadev** [comment]
@jacquesh In bulk search does openlyrics search with only selected sources or all like in manual search ?

**Comment by jacquesh** [comment]
Closing this as a duplicate  of #215. Manual search is irrelevant, because you always pick a specific lyric anyway. In both cases we're concerned with the behaviour of auto-selecting a result from a search.

**Comment by Rexadev** [comment]
Prefer synced lyrics option v1.10 solves it a little
