### ISSUE TITLE
OpenLyrics 1.10.1 crashes foobar2000

### ISSUE THREAD

**Issue by gabriels1963** [jacquesh/foo_openlyrics#387]
Using the shorcut menu to edit an empty lyrics (want to add my own) it crashes f2k.

#### Steps to reproduce
3. Play a song without lyrics
4. Using a shorcut (I've set Alt+E) to edit lyrics 
5. FB2K crashes

#### Expected behavior
Lyrics Editor should be opened

#### Versions
* foobar2000 version: v2.1.5 32-bit
* OpenLyrics version: 1.10.1

#### Debug logs
[failure_00000001.txt](https://github.com/user-attachments/files/16825856/failure_00000001.txt)
[failure_00000001.dmp](https://github.com/user-attachments/files/16825857/failure_00000001.dmp)

**Comment by Rexadev** [comment]
+1

**Comment by jacquesh** [comment]
Thanks for reporting, you don't even need a shortcut, you can do the same via the context menu on the playlist view. Fixed, I'll try put out a new release today.
