### ISSUE TITLE
"Search for lyrics (manually)" uses all available sources.

### ISSUE THREAD

**Issue by Foobartius** [jacquesh/foo_openlyrics#392]
Is it expected behaviour to have ALL sources return results when using "Search for lyrics (manually)", instead of using only those sources listed under: Search sources/Search order?

![Search sources](https://github.com/user-attachments/assets/bb46fa1e-0a7c-4c36-af00-b285a3462522)

If it's expected, and not a bug, could it be possible to add the option to exclude: Search sources/Available sources?

It's mainly a problem for me when I listen to certain genres, or music in languages other than english, because most of the results I get come from NetEase (that I have under "Available sources"). And, that abundance of results is because it tends to return a ton of empty lyrics, with only 1 or 2 lines indicating the composer/lyricist (along the lines of [#242](https://github.com/jacquesh/foo_openlyrics/issues/242)). So, I would like to exclude NetEase, if possible. That way I would only get actual results.

![Search for lyrics (manually)](https://github.com/user-attachments/assets/4217a4d2-aa87-431a-916b-b99a50ac265d)
(In this example, all of the NetEase results did not contain any lyrics.)

Other (Hydrogenaudio) users are apparently seeing similar behaviour, too: summarized [here](https://hydrogenaud.io/index.php/topic,120812.msg1047823.html#msg1047823) (responding to a previous commenter).

Thank you.

**Comment by jacquesh** [comment]
> Is it expected behaviour to have ALL sources return results when using "Search for lyrics (manually)",
Yes

> If it's expected, and not a bug, could it be possible to add the option to exclude: Search sources/Available sources?
Yes. See #149, which this duplicates.
