### ISSUE TITLE
Version 1.11 working great

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#395]
Thanks for this release.  Fast as lightening, and the new Bandcamp source is much appreciated.  The ability to see the source of the lyrics in the "About current lyrics" context menu choice, present since 1.10, also deserves a shout-out.

**Comment by jacquesh** [comment]
I'm glad it's working well for you! :)

Honestly given the size of v1.10, I was expecting more bugs but at least so far it seems to be fairly solid (and hopefully now that I've said this I don't get a deluge of major bug reports >_<)
