### ISSUE TITLE
Lyric Info Panel counts opening manual search as edit

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#406]
#### Versions
* foobar2000 version: 2.15
* OpenLyrics version:

**Comment by jacquesh** [comment]
Please actually fill out the form. Closing until you do as per the bug template instructions.

Running an auto-edit is considered an edit, it could be that there's an auto-edit running when you save the manual search result. Please provide debug logs along with the state of your auto-edit settings and the exact text shown in the manual search preview panel before you save then lyrics, along with the contents of the lyrics after saving.
