### ISSUE TITLE
Support showing lyrics in a transparent window outside of foobar

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/foo_openlyrics#41]
Requested in several places but for example @ https://www.reddit.com/r/foobar2000/comments/mm70rb/i_made_an_opensource_alternative_to/h7uijix/

> Desktop Lyrics, a feature that ESLyrics has it (if you manage to do this basically you'll retire the old component, haha :) ) . I know this was already suggested and your answer was to use View - OpenLyrics panel, but it's not the same. That window from ESLyrics is transparent, you see ONLY the lyrics, so you can do anything you want, with foobar minimized and without any window.

**Comment by Reapor-Yurnero** [comment]
thumb up for this. would be super useful

**Comment by Reapor-Yurnero** [comment]
just curious, is there any plan for this feature?

**Comment by jacquesh** [comment]
Not one that expect to execute particularly soon. I recognise that its a thing people want and I can see the use-case so it seems reasonable to add it at some point. I'm not particularly motivated to build it right now though so if somebody wants to put together a PR with it, I'd consider that but otherwise I expect I'll get to it eventually.
