### ISSUE TITLE
Prioritize local .lrc file before grabbing lyrics from the internet.

### ISSUE THREAD

**Issue by Posiplusive** [jacquesh/foo_openlyrics#424]
Hi. I would like to request that the plugin should not search for lyrics when there's already one with the same name as the song in the same directory. Right now I see no option to do that, and I'd like this report to be considered.

**Comment by jacquesh** [comment]
This is already possible. You should set `Local files` to the first source in the list of enabled sources (and make sure that source is configured to search in the directory containing the track), they get searched in order.
