### ISSUE TITLE
Not see lyric file

### ISSUE THREAD

**Issue by lollita** [jacquesh/foo_openlyrics#427]
I haven't loaded existing texts for some time.
Only the editor for new texts works.

**Comment by jacquesh** [comment]
Please include a detailed description of the problem, along with debug-level logs of a minimal reproduction as per the issue template.

**Comment by lollita** [comment]
Opening track for playback: "C:\Mp3\test.mp3"
INFO-OpenLyrics: New album art data retrieved
INFO-OpenLyrics: Ignoring request to compute zero-size background image
INFO-OpenLyrics: LyricPanel::compute_background_image took 30us
INFO-OpenLyrics: LyricPanel::on_album_art_retrieved took 1704us
INFO-OpenLyrics: Ignoring request to compute zero-size background image
INFO-OpenLyrics: LyricPanel::compute_background_image took 17us
INFO-OpenLyrics: LyricPanel::compute_background_image took 684us
INFO-OpenLyrics: LyricPanel::compute_background_image took 29204us
INFO-OpenLyrics: Creating new display font handle

I have "Local files" only in search Order.
Same directory as the track
[%filename%].lrc
also [%path%][%filename%].lrc not work.

**Comment by lollita** [comment]
also not work original: $replace([%artist% - ][%title%],/,-,\,-,<,-,>,-,:,-,",-,|,-,?,-,*,-)

**Comment by lollita** [comment]
How to do?

**Comment by jacquesh** [comment]
Looks like it's not even trying to search at all...which I think is the same issue as #434

**Comment by lollita** [comment]
If I use "search for lyric" it download ad file saved in .\foobar2000\profile\lyrics\ work also after.
I try old versions, also foo_openlyrics-v1.3 and delete foo_openlyrics.dll.cfg, but load lyric in same path of mp3 file not work.
Maybe a problem with portable version?

**Comment by lollita** [comment]
"Same directory as the track" not work.

**Comment by lollita** [comment]
If I use "search for lyric" it load from same directory as the track but not handle file ansi with accenteded characters.
