### ISSUE TITLE
Romaji lyrics converter

### ISSUE THREAD

**Issue by Kitsune2431** [jacquesh/foo_openlyrics#429]
Not sure how hard it's to implement or if it's possible at all, but it'd be nice if we could convert japanese lyrics to readable format like in spicetify lyrics plus https://github.com/spicetify/cli/tree/main/CustomApps/lyrics-plus

**Comment by jacquesh** [comment]
So essentially translation? You want to convert kanji into romaji? That's beyond the scope of openlyrics and would be better done with external tools.
