### ISSUE TITLE
Support for local transcription tools like Whisper

### ISSUE THREAD

**Issue by dinfinity** [jacquesh/foo_openlyrics#431]
This might be something out of scope of the plugin, but I do think it goes pretty well together.

The feature would be this: Add a context menu option to run a local executable that transcribes the current audio file, with the output being automatically loaded into Openlyrics (with some postprocessing, possibly uploading).

I've been doing this with [Faster-Whisper-XXL](https://github.com/Purfview/whisper-standalone-win), combined with the Run services (foo_run) plugin. It basically calls a batch file:
```
C:\Programs\Faster-Whisper-XXL\GenerateLyrics.bat "%_path%"
```

```bat
:: @echo off

:: Extract the directory of the input file (first argument)
set "input_dir=%~dp1"

:: Add slashes. Apparently faster whisper does this for the input file, but not the output dir.
set "input_dir=%input_dir:\=\\%"

:: Run the command using the extracted directory
C:\Programs\Faster-Whisper-XXL\faster-whisper-xxl.exe --beep_off --ff_mdx_kim2 --model=large-v2 --output_dir="%input_dir%" --output_format=lrc "%~1"
```

With the vocals extraction preprocessing step in Faster-whisper-xxl now added, the results are close to perfect in my experience. Especially for rare songs, this is a really nice thing to have.

**Comment by jacquesh** [comment]
That's pretty neat, I should try that out.
Since you already have a solution for this (namely: use `foo_run`) I'm going to say this is out of scope for openlyrics
