### ISSUE TITLE
Manual search stuck at genius.com

### ISSUE THREAD

**Issue by ChuZhiShen** [jacquesh/foo_openlyrics#44]
Whenever searching for lyric, the search will stuck on genius.com for a longer period of time. Resulting in bad user experience.
Preferable if given option to remove some source from manual searching.

**Comment by jacquesh** [comment]
What is a "longer period of time"? 30 seconds? 5 minutes? Also does this happen when you visit genius.com normally in a browser? This should be somewhat better now with the parallel search.
