### ISSUE TITLE
Auto search can't handle multiple artist vorbis comment

### ISSUE THREAD

**Issue by ChuZhiShen** [jacquesh/foo_openlyrics#45]
when the tag(vorbis comment) consist multiple artists, for example : 
title=A Song Title
artist=ArtistOne
artist=ArtistTwo

The automatic lyric searching will fail to retrieve lyric, where manual searching was available to retrieve correct lyric

**Comment by jacquesh** [comment]
Dupe of #38. Fixed in the next release.
