### ISSUE TITLE
About current lyrics

### ISSUE THREAD

**Issue by anazzani** [jacquesh/foo_openlyrics#52]
Add a context menu "About current lyrics" showing the source (or maybe even automatically show it somewhere?).

From #51

**Comment by jacquesh** [comment]
As requested in #189, we could also show when the lyrics were retrieved (or at least last modified)

**Comment by Rexadev** [comment]
Edit the `Lyric Info` Panel -

## Suggestion -

```
Type			Un/Synced
Source			Retrieved from Metadata tags/URL		<--  Remove `@ SYNCEDLYRICS`
Downloaded		YYYY-MM-DD HH:MM:SS				<--  Remove `@ SYNCEDLYRICS`
Edited			Never/YYYY-MM-DD_HH:MM:SS
```

## Current -
```
Synced lyrics
Retrieved from Metadata tags @ SYNCEDLYRICS
First retrieved from Metadata tags at YYYY-MM-DD HH:MM:SS @ SYNCEDLYRICS
Never edited
```


Retrieved from Metadata tags @ SYNCEDLYRICS

**Comment by Rexadev** [comment]
@jacquesh [Bug] `Lyric Info` Panel counts opening manual search as edit

**Comment by jacquesh** [comment]
Open an issue.
