### ISSUE TITLE
Auto search vs Manual search

### ISSUE THREAD

**Issue by anazzani** [jacquesh/foo_openlyrics#55]
Sometimes I play a song and no lyrics are found, but if I do a manual search I get many results: what could be the reason?

From #51

> The auto-search does some of its own filtering (you may have noticed that the manual search often returns some results that are obviously not what you wanted). If manual search shows a result that exactly matches the artist/album/title tags you have then it should have been found by the auto-search though, so if that's not the case then that's a bug.

I'm pretty sure some of the results had the same artist/album/title tags but I don't have an example at hand: will post one in a couple of weeks if needed.

Furthermore, sometimes I don't have the album tag or it's a VVAA album (but I always have artist/title) so maybe skip that check if no results are found automatically? Or perhaps even better add an option to NOT use album tag when searching?

**Comment by jacquesh** [comment]
As tracked by #39, there was an issue where album info was always required. This has been fixed in the upcoming v0.9 which should resolve this issue. Feel free to re-open it if that is not the case.
