### ISSUE TITLE
Feature request: Ability to search for lyrics from track context menu

### ISSUE THREAD

**Issue by SpamReceiver** [jacquesh/foo_openlyrics#61]
I'd like to ask for the feature to trigger the search for lyrics via the context menu.
Right-click on an entry in the album tree or in the playlist window, select "Search for lyrics".
Should be possible for multiple selections, too.

**Comment by jacquesh** [comment]
Duplicate of #58 (although the name would not suggest it, if you don't mind I'm going to steal your issue title and use it there :D)

**Comment by SpamReceiver** [comment]
Yes, thank you very much! #58 describes what I ask, too.
