### ISSUE TITLE
When lyrics are saved, track number is set to 0

### ISSUE THREAD

**Issue by SpamReceiver** [jacquesh/foo_openlyrics#62]
Strange observation:
When a track is played without a track number (%track% doesn't exist), and lyrics a re searched and found, the track number will be set to 0 in the moment the lyrics are saved.

Steps to reproduce:
1. Configure OpenLyrics for auto-save to tag
2. Play a track where 
   * %track% (track number) doesn't exist 
   * but lyrics exist on one of the sources

Expected:
3. OpenLyrics searches for lyrics and finds some
4. OpenLyrics saves lyrics to tag
5. No other tags are touched

Observed:
3. OpenLyrics searches for lyrics and finds some
4. OpenLyrics saves lyrics to tag
5. %track% (track number) is updated and set to 0 (zero)

**Comment by jacquesh** [comment]
Odd. Do you know if this happens in LSP3 (for example)?

**Comment by SpamReceiver** [comment]
What is LSP3?

**Comment by jacquesh** [comment]
[Lyric Show Panel 3](https://www.foobar2000.org/components/view/foo_uie_lyrics3), the thing people used to use for lyrics (which is no longer maintained and largely not working). It's the thing openlyrics was created to replace :)

**Comment by SpamReceiver** [comment]
I uninstalled LSP3 after I saw OpenLyrics working well. I can't answer the question if the issue appears with LSP3.

Have you been able to reproduce the issue?

**Comment by SpamReceiver** [comment]
I re-installed LSP3, played a track without track number and without lyrics. 
Lyrics were found and saved, but track number was also updated to 0 (zero).

**Comment by SpamReceiver** [comment]
For completeness:
If no lyrics are found, the track number will not be modified and stays empty.

**Comment by jacquesh** [comment]
Oh awesome, thanks for checking that. I haven't checked the tag-saving code in openlyrics recently but I do remember there being concerns about overwriting tags that are not the ones you're specifically changing. It is entirely possible that I've done this incorrectly (the docs are rather sparse on this).

LSP3 doing the same makes me feel just a little bit better but of course its always possible that we're both wrong >_<

Although I'm trying to reproduce it now and it appears to be functioning as you expected. Delete lyrics and track number for track, set saving to tag, search for lyrics, lyrics found and saved to tag, track number still 0. =/

Where are you seeing the track number update to zero. Is it possible that whatever you're using to view them is misrepresenting the available information and just showing 0 if there isn't a track number set? I don't actually know the details of how ID3 tags are stored in the file but at least in one of the tools I use to fiddle with them [kid3](https://kid3.kde.org/), I actually can't "delete" the track number tag, it just clears the value and still shows in the list of tags (unlike other, less standard tags like album artist or lyrics). Similarly if I open the foobar dialog for the track properties (right-click -> properties in the playlist view) it does still have the row for "Track Title", there's just nothing there (its just blank, not a zero).

**Comment by jacquesh** [comment]
Oh, also just to be sure: what version of OpenLyrics are you using? 0.9?

**Comment by SpamReceiver** [comment]
Hello Jaques! 
I currently use Open Lyrics 0.9. 

Referring to your question of "whatever you're using to view them":
I used the playlist view and the properties window of foobar2000 to check the values before and after the lyrics update.

Because of your question, I used a different tool today (MP3Tag https://www.mp3tag.de/).
Well, what should I say:
The 0 track numbers were already there! Before the lyrics update!

It's just that foobar2000 doen't re-read the tags on startup and hence just didn't notice the change.
After saving the lyrics, all tags seem to be re-read from the file and -- oops -- the 0 track numbers show up.

The question of where the 0 track numbers came from, is a different story, but nothing for this discussion.

I have to beg your pardon for the noise here!
Please apologize and close the issue.

**Comment by jacquesh** [comment]
Haha no problem. I'm glad you managed to resolve the issue! :)
