### ISSUE TITLE
Accent not work in ANSI files

### ISSUE THREAD

**Issue by lollita** [jacquesh/foo_openlyrics#75]
Accents not work in files saved in ANSI but only file save in UTF-8.

**Comment by jacquesh** [comment]
Can you be more specific? What were you saving that didn't work? What did it do instead? etc

Ideally openlyrics would save everything as UTF8 but currently it doesn't actually enforce that, so thats certainly something we could add to the TODO list if its what you're after?

**Comment by lollita** [comment]
I have many accented ANSI files created by MiniLyrics and I can't use them with foo_openlyrics.

**Comment by jacquesh** [comment]
Please upload some examples

**Comment by lollita** [comment]
Try thix.
[Joe Cocker - Tonight.lrc.txt](https://github.com/jacquesh/foo_openlyrics/files/7504286/Joe.Cocker.-.Tonight.lrc.txt)

**Comment by bservet** [comment]
For me this mostly happens with the apostrophe:

You get things like: you&apos;re instead of you're.

Or is this caused by something else?

**Comment by lollita** [comment]
Now it work in panel ed edit, but have problem in search for lyric manually text area.

**Comment by jacquesh** [comment]
See #183  about 64-bit

Please rather open a new issue instead of resurrecting a 6-month old one. In that new issue: Can you please be more specific about "have problem" means? What problem? What behaviour are you expecting and what behaviour do you get instead?
