### ISSUE TITLE
Lyric timestamp support for long tracks

### ISSUE THREAD

**Issue by hpewd** [jacquesh/foo_openlyrics#78]
Hi all,

I am mainly using FB2K and w/ it OL to listen to DJ sets. These sets are typically several ours long, which is the reason I am using the id3 lyrics to show the tracklist (instead of regular lyrics). However, synched lyrics only work correctly for me in the following two cases:

1. For timestamps less than one hour, i.e. [00:59:59.99], it works; however values above these, e.g. [01:23:45.67] (hh:mm:ss:ms), are not supported; in such cases the last highlighted timestamp for the rest of the track duration is the one that starts before [01:00:00.00].
2. If I modify the timestamp format from [hh:mm:ss.ms] to [mm:ss.ms] with values less or equal to [99:59.99]; for any value above this OL just highlights the last timestamp that starts before or including [99:59.99] for the rest of the track duration.

Below is an example of how it looks for me. In the image the current play time is [03:23:03.00], but it is not highlighted correctly.
![grafik](https://user-images.githubusercontent.com/41539459/142596067-2887ca01-673d-4467-82f9-d9850a16f6b2.png)

Is this something that can be fixed? I've read on [id3.org](https://id3.org/id3v2.3.0#sec4.10) that synchronised lyrics/text via the SYLT frame allow for either MPEG frames or milliseconds as absolute time units of max. size of 32bit. At a quick glance I'd say that would allow for 2^32 ms > 1000 h.

Hope to find y'all in good spirits,
Hannes

**Comment by jacquesh** [comment]
Its actually simpler than that. The parser just assumes a valid timestamp must be of the form `[00:00.00]` :)

I can certainly take a look at supporting tags with an hour in them though.

**Comment by hpewd** [comment]
That'd be great, thank you :)
