### ISSUE TITLE
Support timestamps with 3 digits for the second fraction

### ISSUE THREAD

**Issue by dinfinity** [jacquesh/foo_openlyrics#79]
Especially in timestamped lyrics from NetEase, the format of the timestamps is this:
[00:00.810]

foo_openlyrics expects exactly two digits at the end, which prevents such (valid) timestamps from being processed.

In `src/parser/lrc.cpp:try_parse_timestamp` you could quite easily use this for the string to double conversion:
https://www.programiz.com/cpp-programming/string-float-conversion

Probably also best to use a regular expression with capture groups for checking valid format and extracting the parts:
https://www.regular-expressions.info/stdregex.html

**Comment by jacquesh** [comment]
There is already an auto-edit for fixing this (rounding to 2 decimal places). Do you have a source for the claim that timestamps with 3 decimal places are valid? I do not know of any "official" spec for the format and nothing I could find suggested that 3 is just as sensible as 2 (and most are just 2).

**Comment by dinfinity** [comment]
Perhaps the auto-edit should be applied after an LRC is loaded from an external source, then (although I think that properly parsing the timestamps is a much better idea). 

With regard to the validity: If no spec exists, technically _every_ number of decimals is valid. Seconds can be infinitely and arbitrarily split up. To imply that nothing smaller beyond centiseconds is valid is quite dubitable.

Probably best to check for yourself what happens when you load a NetEase LRC with three decimals and how that affects foo_openlyrics. Search manually for 'Simon & Garfunkel - Keep The Customer Satisfied', for instance.
