### ISSUE TITLE
Save to the same-directory as the tack is not working non-ANSI path

### ISSUE THREAD

**Issue by AlanBAKA** [jacquesh/foo_openlyrics#94]
the "Save to the same-directory as the tack" option is not working on non-ANSI characters path, like path with Japanese or Korean characters

**Comment by jacquesh** [comment]
What do you mean by "not working"? What does it do and what do you expect it to do instead?

When this happens, does the console (Menu Bar -> View -> Console) show any warnings or errors for OpenLyrics?

**Comment by jacquesh** [comment]
Closing this because I just tried it with a directory that contained Japanese and Korean characters, it seemed to work fine. Open a new ticket if you're still experiencing this on the latest release and please include some more info.
